### ISSUE TITLE
compile elf.ksy error

### ISSUE THREAD

**Issue by GoodBoyCC** [kaitai-io/kaitai_struct#181]
when i try to compile the elf.ksy, a exception occurred as follows:

KS compilation error:  io.kaitai.struct.format.YAMLParseException: /instances/strings/size: invalid type: expected integer, got SwitchType(Attribute(Attribute(Name(identifier(_root)),identifier(header)),identifier(bits)),Map(EnumByLabel(identifier(bits),identifier(b32)) -> IntMultiType(false,Width4,le), EnumByLabel(identifier(bits),identifier(b64)) -> IntMultiType(false,Width8,le)))

ask for help

**Comment by GoodBoyCC** [comment]
And this is the exception info:

Exception in thread "main" io.kaitai.struct.format.YAMLParseException: /instances/strings/size: invalid type: expected integer, got SwitchType(Attribute(Attribute(Name(identifier(_root)),identifier(header)),identifier(bits)),Map(EnumByLabel(identifier(bits),identifier(b32)) -> IntMultiType(false,Width4,le), EnumByLabel(identifier(bits),identifier(b64)) -> IntMultiType(false,Width8,le)))
        at io.kaitai.struct.format.YAMLParseException$.exprType(YAMLParseException.scala:44)
        at io.kaitai.struct.precompile.TypeValidator.checkAssert(TypeValidator.scala:137)
        at io.kaitai.struct.precompile.TypeValidator.validateDataType(TypeValidator.scala:86)
        at io.kaitai.struct.precompile.TypeValidator.validateDataType(TypeValidator.scala:90)
        at io.kaitai.struct.precompile.TypeValidator.validateAttr(TypeValidator.scala:74)
        at io.kaitai.struct.precompile.TypeValidator$$anonfun$validateClass$2.apply(TypeValidator.scala:41)
        at io.kaitai.struct.precompile.TypeValidator$$anonfun$validateClass$2.apply(TypeValidator.scala:38)
        at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
        at io.kaitai.struct.precompile.TypeValidator.validateClass(TypeValidator.scala:38)
        at io.kaitai.struct.precompile.TypeValidator.run(TypeValidator.scala:24)
        at io.kaitai.struct.Main$.precompile(Main.scala:38)
        at io.kaitai.struct.Main$$anonfun$importAndPrecompile$1$$anonfun$apply$2.apply(Main.scala:27)
        at io.kaitai.struct.Main$$anonfun$importAndPrecompile$1$$anonfun$apply$2.apply(Main.scala:26)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
        at io.kaitai.struct.Main$$anonfun$importAndPrecompile$1.apply(Main.scala:26)
        at io.kaitai.struct.Main$$anonfun$importAndPrecompile$1.apply(Main.scala:23)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by GreyCat** [comment]
Can't replicate this error with current elf.ksy and current compiler. This was an issue in previous versions that was fixed in 0.8, and, in fact, current elf.ksy has `ks-version: 0.8`, so it's kind of mysterious how you've got it — if you're using 0.7 release, then probably you would get message about invalid compiler version.

**Comment by GoodBoyCC** [comment]
thanks!

my elf.ksy is weird, when i change to the newest elf.ksy and the compiler of 0.8, the problem has been solved.

**Comment by GreyCat** [comment]
Thanks for the report!
