### ISSUE TITLE
Unable to determine type for `field` in type List(kaitai_struct)

### ISSUE THREAD

**Issue by aki017** [kaitai-io/kaitai_struct#26]
Reproduce gist: https://gist.github.com/aki017/70266d164354696535b9eabcd5a9306c

It occur when nest type and using `_parent.field`

work
```yaml
- id: work
  size: _parent.size
```

broken
```yaml
- id: broken
  size: _parent.size * 2
```

== Error

```
... compiling it for ruby... ... => ./ruby/broken.rb
java.lang.RuntimeException: Unable to determine type for main_size in type List(kaitai_struct)
	at io.kaitai.struct.ClassCompiler.determineType(ClassCompiler.scala:162)
	at io.kaitai.struct.translators.BaseTranslator.detectType(BaseTranslator.scala:260)
	at io.kaitai.struct.translators.BaseTranslator.translate(BaseTranslator.scala:45)
	at io.kaitai.struct.languages.LanguageCompiler.expression(LanguageCompiler.scala:74)
	at io.kaitai.struct.languages.RubyCompiler.parseExpr(RubyCompiler.scala:201)
	at io.kaitai.struct.languages.EveryReadIsExpression$class.attrBytesTypeParse(EveryReadIsExpression.scala:80)
	at io.kaitai.struct.languages.RubyCompiler.attrBytesTypeParse(RubyCompiler.scala:10)
	at io.kaitai.struct.languages.EveryReadIsExpression$class.attrParse2(EveryReadIsExpression.scala:61)
	at io.kaitai.struct.languages.RubyCompiler.attrParse2(RubyCompiler.scala:10)
	at io.kaitai.struct.languages.EveryReadIsExpression$class.attrParse(EveryReadIsExpression.scala:39)
	at io.kaitai.struct.languages.RubyCompiler.attrParse(RubyCompiler.scala:10)
	at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$3.apply(ClassCompiler.scala:100)
	at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$3.apply(ClassCompiler.scala:100)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:100)
	at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$5.apply(ClassCompiler.scala:108)
	at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$5.apply(ClassCompiler.scala:108)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:108)
	at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$5.apply(ClassCompiler.scala:108)
	at io.kaitai.struct.ClassCompiler$$anonfun$compileClass$5.apply(ClassCompiler.scala:108)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:137)
	at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:108)
	at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:80)
	at io.kaitai.struct.Main$.compileOne(Main.scala:84)
	at io.kaitai.struct.Main$$anonfun$compileAll$1.apply(Main.scala:97)
	at io.kaitai.struct.Main$$anonfun$compileAll$1.apply(Main.scala:93)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at io.kaitai.struct.Main$.compileAll(Main.scala:93)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:118)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.Main$.main(Main.scala:111)
	at io.kaitai.struct.Main.main(Main.scala)
```

**Comment by GreyCat** [comment]
That is definitely some problem with handling nested types with same names - i.e. `broken::main::foo` and `broken::dummy::foo` - it looks like parent type derivation breaks in some cases. I'll try to investigate it further.

**Comment by GreyCat** [comment]
Thanks for the report, by the way! Appreciate it :)

**Comment by GreyCat** [comment]
Note that this one is actually a bad idea to do:

```yaml
  main:
    seq:
      - id: foo
        type: foo
      - id: main_size
        type: s4
    types:
      foo:
        seq:
          - id: data
            size: (_parent.main_size) * 2
```

You start reading `main` with reading `foo` subelement, which immediately proceeds to read as many bytes as there is in `_parent` (i.e. `main` object's) `main_size`, doubled. However, `_parent.main_size` at that point is still undefined, as the actual reading of `main_size` is done later. This won't work, but we can swap these and the type check error is still there.

**Comment by aki017** [comment]
Thanks for pointing it out.
I updated gist(reorder that fields).

**Comment by GreyCat** [comment]
You can check out latest compiler commit - it features rewrite of parent type handling procedures, and should fix this issue. However, it breaks some other stuff like value instance type derivation (i.e. tests like `expr_0`), I'll try to fix it later.

**Comment by aki017** [comment]
ok, new compiler seems working, but still have (maybe) same issue.
I created new gist https://gist.github.com/aki017/74872626de033349713bf800cac4dfdf

`broken::main::foo` is work, but `broken::dummy::foo` cause same error
> Unable to determine type for dummy_size in type List(kaitai_struct)

or something build problem?(i cant use scala)

**Comment by GreyCat** [comment]
I've finished work on new type engine, your last gist is added as [nested_same_name2](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/nested_same_name2.ksy) test (the only thing I've changed besides meta ID is that first and second "foo" types now use slightly different attribute names - `data1` and `data2` to make it possible to check that proper `foo` is instances). It seems to pass properly.

**Comment by GreyCat** [comment]
@aki017 Things seem to work now, so I'm closing this issue. Thanks again for your concern!
