### ISSUE TITLE
Can't use exponent (**) expressions in instances->value

### ISSUE THREAD

**Issue by erikpotterbsx** [kaitai-io/kaitai_struct#296]
I get a parse error both in the IDE and on the command line when trying to use the ** exponentiation expression.
`skin_temp` is the name of the instance I'm referencing. If I remove one of the asterisks ** -> * it parses just fine using multiplication.

This is the universal download of Kaitai Struct 0.7 from the website.
```
Exception in thread "main" io.kaitai.struct.exprlang.Expressions$ParseException: End:1:11 ..."* (skin_te"                                             
        at io.kaitai.struct.exprlang.Expressions$.parse(Expressions.scala:173)                                                                        
        at io.kaitai.struct.format.InstanceSpec$$anonfun$1.apply(InstanceSpec.scala:39)                                                               
        at io.kaitai.struct.format.InstanceSpec$$anonfun$1.apply(InstanceSpec.scala:39)                                                               
        at scala.Option.map(Option.scala:146)                                                                                                         
        at io.kaitai.struct.format.InstanceSpec$.fromYaml(InstanceSpec.scala:39)                                                                      
        at io.kaitai.struct.format.ClassSpec$$anonfun$instancesFromYaml$1.apply(ClassSpec.scala:127)                                                  
        at io.kaitai.struct.format.ClassSpec$$anonfun$instancesFromYaml$1.apply(ClassSpec.scala:123)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
        at scala.collection.MapLike$MappedValues$$anonfun$foreach$3.apply(MapLike.scala:245)
        at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
        at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
        at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:245)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at io.kaitai.struct.format.ClassSpec$.instancesFromYaml(ClassSpec.scala:123)
        at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:77)
        at io.kaitai.struct.format.ClassSpec$$anonfun$typesFromYaml$1.apply(ClassSpec.scala:117)
        at io.kaitai.struct.format.ClassSpec$$anonfun$typesFromYaml$1.apply(ClassSpec.scala:115)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at io.kaitai.struct.format.ClassSpec$.typesFromYaml(ClassSpec.scala:115)
        at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:73)
        at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:140)
        at io.kaitai.struct.formats.JavaKSYParser$.fileNameToSpec(JavaKSYParser.scala:29)
        at io.kaitai.struct.formats.JavaKSYParser$.localFileToSpecs(JavaKSYParser.scala:18)
        at io.kaitai.struct.JavaMain.io$kaitai$struct$JavaMain$$compileOneInput(JavaMain.scala:216)
        at io.kaitai.struct.JavaMain$$anonfun$15.apply(JavaMain.scala:199)
        at io.kaitai.struct.JavaMain$$anonfun$15.apply(JavaMain.scala:197)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.immutable.List.map(List.scala:285)
        at io.kaitai.struct.JavaMain.run(JavaMain.scala:197)
        at io.kaitai.struct.JavaMain$.main(JavaMain.scala:188)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
```

**Comment by erikpotterbsx** [comment]
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/216
