### ISSUE TITLE
Have anyone run the compiler with JRE 8u161?

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#349]
I have recently updated the JRE on Windows machine from 8u151 to 8u161 and saw that KSC started crashing.

<details>
<summary>The error message</summary>
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab6 0060 04a0 001e b200 b8b2 00bd 04bd
    0x0000010: 0002 5903 2a53 c000 bfb6 00c3 b600 c7c0
    0x0000020: 00c9 b02a b600 36b8 0040 3c1b 04a4 015e
    0x0000030: 1b05 6c3d 2a1b 056c 2ab6 0036 b700 cb3e
    0x0000040: 2ab6 0036 021d 787e 3604 2ab6 0036 0210
    0x0000050: 201d 647c 7e36 05bb 0019 59b2 00bd 2ab6
    0x0000060: 0038 c000 bfb6 00cf b700 d21c b600 d63a
    0x0000070: 0619 06c6 001a 1906 b600 dac0 0086 3a07
    0x0000080: 1906 b600 ddc0 0086 3a08 a700 0dbb 00df
    0x0000090: 5919 06b7 00e2 bf19 073a 0919 083a 0abb
    0x00000a0: 0002 5915 0419 09bb 0019 59b2 00bd 1909
    0x00000b0: c000 bfb6 00cf b700 d203 b800 e83a 0e3a
    0x00000c0: 0d03 190d b900 ec01 0019 0e3a 1136 1036
    0x00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    0x00000e0: 150f b900 ef02 00c0 0005 3a17 1911 1917
    0x00000f0: b800 f33a 1136 1036 0fa7 ffd8 1911 b800
    0x0000100: f7b7 0065 3a0b bb00 0259 1505 190a bb00
    0x0000110: 1959 b200 bd19 0ac0 00bf b600 cfb7 00d2
    0x0000120: 03b8 00e8 3a13 3a12 0319 12b9 00ec 0100
    0x0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0x0000140: 1404 6015 1519 1215 14b9 00ef 0200 c000
    0x0000150: 053a 1819 1619 18b8 00fa 3a16 3615 3614
    0x0000160: a7ff d819 16b8 00f7 b700 653a 0cb2 00ff
    0x0000170: b200 bd05 bd00 0259 0319 0b53 5904 190c
    0x0000180: 53c0 00bf b600 c3b6 0102 b02a b600 3803
    0x0000190: 32b6 0104 b0
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114]},{})
    append_frame(@151,Object[#134],Object[#134])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Top,Top,Object[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#159],Uninitialized[#159], Integer,Object[#134]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Top,Top,Object[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#134]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Object[#2],Top,Object[#25],Object[#60],Integer,Integer,Object[#112],Objct[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#134]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Object[#2],Top,Object[#25],Object[#60],Integer,Integer,Object[#112],Objct[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#134]})
    full_frame(@395,{Object[#2],Integer},{})

        at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:182)
        at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:217)
        at scala.collection.immutable.HashMap.updated(HashMap.scala:59)
        at scala.collection.immutable.Map$Map4.updated(Map.scala:201)
        at scala.collection.immutable.Map$Map4.$plus(Map.scala:202)
        at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
        at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
        at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
        at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:59)
        at scala.collection.generic.Growable$$Lambda$7/2113185.apply(Unknown Source)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
        at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
        at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:48)
        at io.kaitai.struct.languages.components.LanguageCompilerStatic$.<init>(LanguageCompilerStatic.scala:23)
        at io.kaitai.struct.languages.components.LanguageCompilerStatic$.<clinit>(LanguageCompilerStatic.scala)
        at io.kaitai.struct.JavaMain$.<init>(JavaMain.scala:27)
        at io.kaitai.struct.JavaMain$.<clinit>(JavaMain.scala)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
</details>

Googling showed that such errors are widespread with scala and usually solved by upgrading JRE but this is one of the latest versions (I have not tried 162 yet).

**Comment by GreyCat** [comment]
Works fine for me with 162. Probably some sort of JVM bug?

**Comment by KOLANICH** [comment]
Maybe, but the rest of java apps I use work fine.

**Comment by KOLANICH** [comment]
I have tried an ancient (march 2017) version of the compiler, it works. Have you updated scala somewhen?

**Comment by KOLANICH** [comment]
The old version of KSC works fine on this JRE. Have you updated scala somewhen?

**Comment by GreyCat** [comment]
Yeah, last update of dependencies was in December: https://github.com/kaitai-io/kaitai_struct_compiler/commit/68635aad96bf713621c50a07b5925f797b0ded5c#diff-fdc3abdfd754eeb24090dbd90aeec2ce

**Comment by GreyCat** [comment]
BTW, I still can't reproduce the issue on a Windows 10 box using:

```
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by KOLANICH** [comment]
I work on XP.

**Comment by GreyCat** [comment]
Um, I'm not even sure I can provision one anywhere nowadays... Does anyone else might confirm the issue by any chance?

**Comment by GreyCat** [comment]
And, as you probably already know, https://www.java.com/en/download/faq/winxp.xml

**Comment by koczkatamas** [comment]
Windows XP is not supported itself for years by now. I think we should not support ancient systems.

**Comment by KOLANICH** [comment]
@GreyCat , I know, the latest version even stopped installing (I guess it is a bug, installer just crashes). But in the installers of the previous versions were messages saying the things like "though it still works its better to upgrade".

**Comment by KOLANICH** [comment]
https://ci.appveyor.com/api/buildjobs/x9mubxtt3en6m5k6/artifacts/compiler%2Fjvm%2Ftarget%2Fwindows%2Fkaitai-struct-compiler.msi - does work, it is the last working build
https://ci.appveyor.com/api/buildjobs/wfb6h1h3y2g9vf0i/artifacts/compiler%2Fjvm%2Ftarget%2Fwindows%2Fkaitai-struct-compiler.msi - doesn't work, this is the build with upgraded scala

**Comment by GreyCat** [comment]
Thanks for confirming it. Could you check if any older versions of JVM (i.e. 8u151 you've mentioned) + WinXP indeed work with latest compiler build?

**Comment by KOLANICH** [comment]
On 151 it worked (it was not the latest compiler by now of course, but it was the latest by that time, for example I have used the one in which you have fixed pcap.ksy problem). Unfortunately Oracle restricts access to old builds of JRE.

**Comment by GreyCat** [comment]
8u151 for Windows should be available here:

http://download.oracle.com/otn-pub/java/jdk/8u151-b12/e758a0de34e24606bca991d704f6dcbf/jre-8u151-windows-x64.exe

I suspect that it could turn out to have nothing to do with these recent JRE updates, and only Scala/SBT version is the culprit. In this case we can probably set up separate set of "WinXP-friendly" builds, patching build.sbt / plugins slightly before build to deliver WinXP-friendly ksc.
