### ISSUE TITLE
ksc cpp_stl error: an implementation is missing AnyType (of class io.kaitai.struct.datatype.DataType$AnyType$)

### ISSUE THREAD

**Issue by cursey** [kaitai-io/kaitai_struct#416]
Hi,

This is my first time playing with kaitai struct so maybe I did something wrong but given the following `.ksy` file: 

```
meta:
  id: packet
  file-extension: packet
  endian: be
  encoding: UTF-8
  imports:
    - vlq_base128_le
seq:
  - id: header
    type: header
  - id: message
    type: message
  - id: checksum
    type: u4
types:
  header:
    seq:
      - id: type
        type: u1
      - id: length
        type: u4le
      - id: zero
        type: u1
  message:
    seq:
      - id: op
        type: u4
      - id: id
        type: u8
      - id: body_length
        type: vlq_base128_le
      - id: element_count
        type: vlq_base128_le
      - id: zero
        type: u1
      - id: elements
        type: element
        repeat: expr
        repeat-expr: element_count.value
  element:
    seq:
      - id: type
        type: u1
        enum: element_type
      - id: value
        type:
          switch-on: type
          cases:
            'element_type::byte': u1
            'element_type::short': u2
            'element_type::int': u4
            'element_type::long': u8
            'element_type::float': f4
            'element_type::string': element_string
            'element_type::bin': element_bin
  element_string:
    seq:
      - id: length
        type: u2
      - id: value
        type: str
        size: length
  element_bin:
    seq:
      - id: length
        type: u2
      - id: value
        size: length
enums:
  element_type:
    1: byte
    2: short
    3: int
    4: long
    5: float
    6: string
    7: bin
```
and compiling it like `kaitai-struct-compiler -t cpp_stl .\packet.ksy --debug` gives me the error message:

```
an implementation is missing
AnyType (of class io.kaitai.struct.datatype.DataType$AnyType$)
```

Here's the output with `--ksc-exceptions`:

```
scala.MatchError: AnyType (of class io.kaitai.struct.datatype.DataType$AnyType$)
        at io.kaitai.struct.languages.CppCompiler.kaitaiType2NativeType(CppCompiler.scala:799)
        at io.kaitai.struct.languages.CppCompiler.kaitaiType2NativeType(CppCompiler.scala:806)
        at io.kaitai.struct.languages.CppCompiler.attributeDeclaration(CppCompiler.scala:235)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileAttrDeclarations$1(ClassCompiler.scala:147)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileAttrDeclarations$1$adapted(ClassCompiler.scala:141)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at io.kaitai.struct.ClassCompiler.compileAttrDeclarations(ClassCompiler.scala:141)
        at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:87)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1(ClassCompiler.scala:239)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1$adapted(ClassCompiler.scala:239)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
        at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:239)
        at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:78)
        at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:25)
        at io.kaitai.struct.Main$.compile(Main.scala:65)
        at io.kaitai.struct.JavaMain.compileSpecAndWriteToFile(JavaMain.scala:282)
        at io.kaitai.struct.JavaMain.$anonfun$compileOneLang$2(JavaMain.scala:265)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at io.kaitai.struct.JavaMain.compileOneLang(JavaMain.scala:263)
        at io.kaitai.struct.JavaMain.compileOneInput(JavaMain.scala:242)
        at io.kaitai.struct.JavaMain.$anonfun$run$1(JavaMain.scala:212)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at io.kaitai.struct.JavaMain.run(JavaMain.scala:210)
        at io.kaitai.struct.JavaMain$.main(JavaMain.scala:201)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
AnyType (of class io.kaitai.struct.datatype.DataType$AnyType$)
```

Any suggestions?

Thanks!

**Comment by GreyCat** [comment]
The problem is this one:

```yaml
          switch-on: type
          cases:
            'element_type::byte': u1
            'element_type::short': u2
            'element_type::int': u4
            'element_type::long': u8
            'element_type::float': f4
            'element_type::string': element_string
            'element_type::bin': element_bin
```

You're combining integers, floats and user types here. C++ (especially the ancient version we support) does not have equivalent of AnyType or Variant — i.e. a standard type that can contain any other type. The ways out are either:

1. Don't use C++
2. Don't use combining primitive types with user types

The latter can be actually unrolled into a somewhat lengthy workaround like that:

```
          switch-on: type
          cases:
            'element_type::byte': element_byte
            'element_type::short': element_short
           # ...
            'element_type::bin': element_bin
types:
  element_byte: # tons of dummy types 
    seq:
      - id: value
        type: u1
  element_short:
    seq:
      - id: value
        type: u2
```

**Comment by cursey** [comment]
Oh alright, that will work fine for now. Thanks!

**Comment by sykhro** [comment]
Since c++17, `std::any` and `std::variant` are available. I see that things are currently limited to c++11, in that case `boost::any` or  [any-lite](https://github.com/martinmoene/any-lite) could work

**Comment by alexkutsan** [comment]
I have similar problem with official `google_protobuf.ksy` example? 
```
$ ksc --target cpp_stl ./google_protobuf.ksy
google_protobuf: /: error: AnyType (of class io.kaitai.struct.datatype.DataType$AnyType$)
```
Any workaround to use Katai Struct in C++?

**Comment by sykhro** [comment]
> I have similar problem with official `google_protobuf.ksy` example.
> 
> ```
> $ ksc --target cpp_stl ./google_protobuf.ksy
> google_protobuf: /: error: AnyType (of class io.kaitai.struct.datatype.DataType$AnyType$)
> ```
> 
> Any workaround to use Katai Struct in C++?

In my own .ksy files I avoid generating AnyType(s). No other way until an AnyType implementation is provided

**Comment by generalmimon** [comment]
> Any workaround to use Katai Struct in C++?

Well, as @GreyCat wrote above (https://github.com/kaitai-io/kaitai_struct/issues/416#issuecomment-380763000):

> 2\. Don't use combining primitive types with user types
> 
> The latter can be actually unrolled into a somewhat lengthy workaround like that:
> 
> ```yaml
>           switch-on: type
>           cases:
>             'element_type::byte': element_byte
>             'element_type::short': element_short
>            # ...
>             'element_type::bin': element_bin
> types:
>   element_byte: # tons of dummy types 
>     seq:
>       - id: value
>         type: u1
>   element_short:
>     seq:
>       - id: value
>         type: u2
> ```

you can do the same thing for [`google_protobuf.ksy`](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/serialization/google_protobuf.ksy). The workaround is simple - modify these lines ([`google_protobuf.ksy:62-68`](https://github.com/kaitai-io/kaitai_struct_formats/blob/5345c5e1939772efc8304ba3fda775aff8ccf082/serialization/google_protobuf.ksy#L62-L68)):

```ksy
        type:
          switch-on: wire_type
          cases:
            'wire_types::varint': vlq_base128_le
            'wire_types::len_delimited': delimited_bytes
            'wire_types::bit_64': u8le
            'wire_types::bit_32': u4le
```

like this:

```diff
         type:
           switch-on: wire_type
           cases:
             'wire_types::varint': vlq_base128_le
             'wire_types::len_delimited': delimited_bytes
-            'wire_types::bit_64': u8le
-            'wire_types::bit_32': u4le
+            'wire_types::bit_64': u8le_wrapper
+            'wire_types::bit_32': u4le_wrapper
     instances:
       wire_type:
@@ ... @@
   delimited_bytes:
     seq:
       - id: len
         type: vlq_base128_le
       - id: body
         size: len.value
+  u8le_wrapper:
+   seq:
+     - id: value
+       type: u8le
+  u4le_wrapper:
+   seq:
+     - id: value
+       type: u4le
```

**Comment by alexkutsan** [comment]
Is there any plans to modify standard examples to be compatible with C++? Or rework C++ generator to support std::variant?

**Comment by GreyCat** [comment]
@alexkutsan In general, creating C++17 mode which will have `std::variant` or `std::any` support makes sense.

If you feel like contributing one, PRs are very welcome :)

**Comment by sykhro** [comment]
There's many std::any implementations that work on C++11 or even 98. I know it would be adding a dependency, but this way there's no need to create a new mode.

**Comment by hakanai** [comment]
Just to clarify this one, is it the case that _this_ case is OK:

```
        type:
          switch-on: size
          cases:
            1: u1
            2: u2
            4: u4
```

But _this_ case is not:

```
        type:
          switch-on: is_common_toon
          cases:
            0: sized_index(_root.header.texture_index_size)
            1: u1
```
