### ISSUE TITLE
Another error message that could be more helpful

### ISSUE THREAD

**Issue by brunchboy** [kaitai-io/kaitai_struct#490]
While trying to set up a parse object that I could use for relative positioning of other instances, I ran into an error message that completely baffled me. I tried creating a `heap` stream [here](
https://github.com/Deep-Symmetry/beat-link/blob/b12142d3b43cc42a45eb3d8a6576b8283b3f7138/kaitai/pdb.ksy#L208-L209), and using it [here](
https://github.com/Deep-Symmetry/beat-link/blob/b12142d3b43cc42a45eb3d8a6576b8283b3f7138/kaitai/pdb.ksy#L295-L297), and the error I received was:
```
kaitai-struct-compiler kaitai/pdb.ksy -t java --outdir target \
                            --java-package org.deepsymmetry.beatlink.pdb.generated --ksc-exceptions
scala.MatchError: BytesEosType(None,false,None,None) (of class io.kaitai.struct.datatype.DataType$BytesEosType)
    at io.kaitai.struct.translators.CommonMethods.translateAttribute(CommonMethods.scala:48)
    at io.kaitai.struct.translators.CommonMethods.translateAttribute$(CommonMethods.scala:8)
    at io.kaitai.struct.translators.BaseTranslator.translateAttribute(BaseTranslator.scala:26)
    at io.kaitai.struct.translators.BaseTranslator.translate(BaseTranslator.scala:116)
    at io.kaitai.struct.languages.components.ObjectOrientedLanguage.expression(ObjectOrientedLanguage.scala:9)
    at io.kaitai.struct.languages.components.ObjectOrientedLanguage.expression$(ObjectOrientedLanguage.scala:9)
    at io.kaitai.struct.languages.JavaCompiler.expression(JavaCompiler.scala:12)
    at io.kaitai.struct.languages.JavaCompiler.useIO(JavaCompiler.scala:283)
    at io.kaitai.struct.languages.components.CommonReads.attrParse(CommonReads.scala:19)
    at io.kaitai.struct.languages.components.CommonReads.attrParse$(CommonReads.scala:11)
    at io.kaitai.struct.languages.JavaCompiler.attrParse(JavaCompiler.scala:12)
    at io.kaitai.struct.ClassCompiler.compileInstance(ClassCompiler.scala:266)
    at io.kaitai.struct.ClassCompiler.$anonfun$compileInstances$1(ClassCompiler.scala:243)
    at io.kaitai.struct.ClassCompiler.$anonfun$compileInstances$1$adapted(ClassCompiler.scala:242)
    at scala.collection.immutable.Map$Map3.foreach(Map.scala:176)
    at io.kaitai.struct.ClassCompiler.compileInstances(ClassCompiler.scala:242)
    at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:83)
    at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1(ClassCompiler.scala:239)
    at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1$adapted(ClassCompiler.scala:239)
    at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
    at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:239)
    at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:78)
    at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:25)
    at io.kaitai.struct.Main$.compile(Main.scala:65)
    at io.kaitai.struct.JavaMain.compileSpecAndWriteToFile(JavaMain.scala:282)
    at io.kaitai.struct.JavaMain.$anonfun$compileOneLang$2(JavaMain.scala:265)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
    at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
    at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
    at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
    at scala.collection.TraversableLike.map(TraversableLike.scala:234)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at io.kaitai.struct.JavaMain.compileOneLang(JavaMain.scala:263)
    at io.kaitai.struct.JavaMain.compileOneInput(JavaMain.scala:242)
    at io.kaitai.struct.JavaMain.$anonfun$run$1(JavaMain.scala:212)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:389)
    at scala.collection.TraversableLike.map(TraversableLike.scala:234)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
    at scala.collection.immutable.List.map(List.scala:295)
    at io.kaitai.struct.JavaMain.run(JavaMain.scala:210)
    at io.kaitai.struct.JavaMain$.main(JavaMain.scala:201)
    at io.kaitai.struct.JavaMain.main(JavaMain.scala)
BytesEosType(None,false,None,None) (of class io.kaitai.struct.datatype.DataType$BytesEosType)
```
@GreyCat explained the issue to me, that you can’t have `._io` for a byte array, and showed how to use a dummy type as a workaround. He agreed that the error message should be fixed to point people in that direction.

**Comment by GreyCat** [comment]
Should be fixed, as of https://github.com/kaitai-io/kaitai_struct_compiler/commit/566b980b04af40fb09496edc6352cd14bba2339f — see [io_on_bytes.ksy](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats_err/io_on_bytes.ksy) for a test.
