### ISSUE TITLE
Recursive Lazy instances not lazy enough

### ISSUE THREAD

**Issue by DarkDimius** [kaitai-io/kaitai_struct#512]
The following example illustrates use of a format where you need to find size of a recursive datastructure that isn't explicitly written but is implicitly encoded.
More specifically, this is indended to count number of continuous bits before a stopbit is hit.

```
meta:
  id: tmp
  file-extension: tmp
  endian: be
seq:
  - id: r
    type: Rec
types:
  Rec:
   seq:
    - id: bit
      type: u1
    - id: nxt
      if: bit < 128 
      type: Rec
   instances:
     count_reverse:
       type: u1
       value: "bit < 128? nxt.count_reverse + 1 : 0"
```

```
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at io.kaitai.struct.TypeProcessor$.getInstanceDataType(TypeProcessor.scala:276)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$2.apply(TypeProcessor.scala:225)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$2.apply(TypeProcessor.scala:224)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at io.kaitai.struct.TypeProcessor$.markupParentTypes(TypeProcessor.scala:224)
	at io.kaitai.struct.TypeProcessor$.markupParentAs(TypeProcessor.scala:260)
	at io.kaitai.struct.TypeProcessor$.markupParentAs(TypeProcessor.scala:249)
	at io.kaitai.struct.TypeProcessor$.markupParentTypesAdd(TypeProcessor.scala:232)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$1.apply(TypeProcessor.scala:222)
	at io.kaitai.struct.TypeProcessor$$anonfun$markupParentTypes$1.apply(TypeProcessor.scala:221)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.TypeProcessor$.markupParentTypes(TypeProcessor.scala:221)
	at io.kaitai.struct.TypeProcessor$.processTypes(TypeProcessor.scala:17)
	at io.kaitai.struct.formats.JavaKSYParser$.localFileToSpec(JavaKSYParser.scala:17)
	at io.kaitai.struct.Main$.compileOne(Main.scala:83)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:120)
	at io.kaitai.struct.Main$$anonfun$main$1.apply(Main.scala:115)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at io.kaitai.struct.Main$.main(Main.scala:115)
	at io.kaitai.struct.Main.main(Main.scala)
```

**Comment by heinermann** [comment]
I ran into a similar case, but my workaround was to unroll the recursion an appropriate amount of times for this format spec, just in case anyone is looking for said workaround:

```yml
  wrap_b1:
    seq:
      - id: value
        type: b1

  itemcode_decoder:
    params:
      - id: index
        type: u4
    seq:
      # having a b1 here instead of a user type forces a byte alignment
      - id: bit
        type: wrap_b1
        if: itemcode3 == 65535
      - id: followup
        type: |
          itemcode_decoder(bit.value ? itemcode1 : itemcode2)
        if: itemcode3 == 65535
    # Recursive instance is impossible
    instances:
      itemcode1:
        value: _root.itemcodebits1[index]
      itemcode2:
        value: _root.itemcodebits2[index]
      itemcode3:
        value: _root.itemcodebits3[index]
      final:
        value: itemcode3 & 0xFF
      result:
        value: "itemcode3 == 65535 ? followup.result1 : final"
      result1:
        value: "itemcode3 == 65535 ? followup.result2 : final"
      result2:
        value: "itemcode3 == 65535 ? followup.result3 : final"
      result3:
        value: "itemcode3 == 65535 ? followup.result4 : final"
      result4:
        value: "itemcode3 == 65535 ? followup.result5 : final"
      result5:
        value: "itemcode3 == 65535 ? followup.result6 : final"
      result6:
        value: "itemcode3 == 65535 ? followup.result7 : final"
      result7:
        value: "itemcode3 == 65535 ? followup.result8 : final"
      result8:
        value: "itemcode3 == 65535 ? followup.result9 : final"
      result9:
        value: "itemcode3 == 65535 ? followup.result10 : final"
      result10:
        value: "itemcode3 == 65535 ? followup.result11 : final"
      result11:
        value: "itemcode3 == 65535 ? followup.result12 : final"
      result12:
        value: "itemcode3 == 65535 ? followup.result13 : final"
      result13:
        value: "itemcode3 == 65535 ? followup.result14 : final"
      result14:
        value: "itemcode3 == 65535 ? followup.result15 : final"
      result15:
        value: "itemcode3 == 65535 ? followup.result16 : final"
      result16:
        value: "itemcode3 == 65535 ? followup.result17 : final"
      result17: # All valid item IDs are covered by this point
        value: final
```

**Comment by generalmimon** [comment]
@heinermann:

> I ran into a similar case, but my workaround was to unroll the recursion an appropriate amount of times for this format spec

Frankly, this looks horrible and it's completely unnecessary to do it this way. It took me quite a while to figure out how this works and what it does because it's written in a very confusing way.

First of all, it's best to avoid this kind of recursion if possible. It's usually much better to use an iterative approach. To pass data from one iteration to the next, you can use `params`. See the example in https://github.com/kaitai-io/kaitai_struct/issues/291#issuecomment-997447273. If you use `params` like this, there won't be any recursion, so you won't have any problems that recursion brings.

I'd suggest the following as a replacement for your .ksy snippet, which should give the same results unless I missed something:

```ksy
types:
  itemcode_decoder:
    params:
      - id: initial_index
        type: s4
    seq:
      - id: items
        type: 'itemcode_decoder_item(_index == 0 ? initial_index : items[_index - 1].next_index)'
        repeat: until
        repeat-until: _root.itemcodebits3[_.next_index] != 65535
        if: _root.itemcodebits3[initial_index] == 65535
    instances:
      final_index:
        value: '_root.itemcodebits3[initial_index] == 65535 ? items.last.next_index : initial_index'
      result:
        value: '_root.itemcodebits3[final_index] & 0xFF'

  itemcode_decoder_item:
    params:
      - id: index
        type: s4
    seq:
      - id: bit
        type: b1
    instances:
      itemcode1:
        value: _root.itemcodebits1[index]
      itemcode2:
        value: _root.itemcodebits2[index]
      next_index:
        value: 'bit ? itemcode1 : itemcode2'
```

**Comment by heinermann** [comment]
Hahaha ok I am still learning, I did not think to do it this way. If you think that looks horrible you should see my first attempt 😭. Thanks this was helpful in improving the spec I'm working on.
