### ISSUE TITLE
don't know how to call anything on CalcArrayType(UserTypeInstream(List(fmt_oms_apl_full_vdb),None,List()))

### ISSUE THREAD

**Issue by ams-tschoening** [kaitai-io/kaitai_struct#561]
I have some type in which I need to access my parent under certain conditions, because it contains a list of types like I am and I need to access a formerly parsed instance of mine. The following is a reduced example to not make things too complicated:

```ksy
  is_possible_meh_0b_vs_4b_vdbs:
    value:  _parent._parent.as<fmt_oms_apl_full_vdb>._parent.vdbs

  is_possible_meh_0b_vs_4b:
    value:  [...] and
            (     is_possible_meh_0b_vs_4b_vdbs.size                       >= 0)    and
            (not  _parent._parent.as<fmt_oms_apl_full_vdb>._parent.vdbs.last.header.dib.dif.is_idle_filler) and
            (     _parent._parent.as<fmt_oms_apl_full_vdb>._parent.vdbs.last.header.dib.storage_nr == 0)
```

As you can see, I would like to avoid repeating myself in the second instance by simply providing the list of values of my type using the first instance. The problem is that using the first instance results in the following error:

    Compilation OK
    ... processing record\clt\fmt_recs_clt.ksy 0
    Error: [{"file"=>"record\\clt\\fmt_recs_clt.ksy", "path"=>["types", "fmt_oms_apl_dib", "instances", "is_possible_meh_0b_vs_4b", "value"], "message"=>"don't know how to call anything on CalcArrayType(UserTypeInstream(List(fmt_oms_apl_full_vdb),None,List()))"}]
    Fatal errors encountered, cannot continue

When I simply remove usage of the first instance and become more verbose again, things work as expected. In the end, I would simply like to store some array in some value instance to access that later.

Is that supported or am I missing something?

**Comment by ams-tschoening** [comment]
I get the following exception during generation of Java:

	scala.MatchError: CalcArrayType(UserTypeInstream(List(fmt_oms_apl_full_vdb),None,List())) (of class io.kaitai.struct.datatype.DataType$CalcArrayType)
	.... writing src/de/am_soft/sm_mtg/format/parser/record/FmtOmsAplVibVifeCombinable.java
		at io.kaitai.struct.languages.JavaCompiler$.kaitaiType2JavaTypeBoxed(JavaCompiler.scala:773)
		at io.kaitai.struct.languages.JavaCompiler.instanceDeclaration(JavaCompiler.scala:574)
		at io.kaitai.struct.ClassCompiler.compileInstanceDeclaration(ClassCompiler.scala:333)
		at io.kaitai.struct.ClassCompiler.compileInstance(ClassCompiler.scala:309)
		at io.kaitai.struct.ClassCompiler.$anonfun$compileInstances$1(ClassCompiler.scala:301)
		at io.kaitai.struct.ClassCompiler.$anonfun$compileInstances$1$adapted(ClassCompiler.scala:300)
		at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
		at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
		at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
		at io.kaitai.struct.ClassCompiler.compileInstances(ClassCompiler.scala:300)
		at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:77)
		at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1(ClassCompiler.scala:297)
		at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1$adapted(ClassCompiler.scala:297)
		at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
		at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
		at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:297)
		at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:72)
		at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:23)
		at io.kaitai.struct.Main$.compile(Main.scala:71)
		at io.kaitai.struct.JavaMain.compileSpecAndWriteToFile(JavaMain.scala:330)
		at io.kaitai.struct.JavaMain.$anonfun$compileOneLang$2(JavaMain.scala:312)
		at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
		at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
		at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
		at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
		at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
		at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
		at scala.collection.TraversableLike.map(TraversableLike.scala:234)
		at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
		at scala.collection.AbstractTraversable.map(Traversable.scala:104)
		at io.kaitai.struct.JavaMain.compileOneLang(JavaMain.scala:310)
		at io.kaitai.struct.JavaMain.compileOneInput(JavaMain.scala:280)
		at io.kaitai.struct.JavaMain.$anonfun$run$1(JavaMain.scala:250)
		at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
		at scala.collection.immutable.List.foreach(List.scala:389)
		at scala.collection.TraversableLike.map(TraversableLike.scala:234)
		at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
		at scala.collection.immutable.List.map(List.scala:295)
		at io.kaitai.struct.JavaMain.run(JavaMain.scala:248)
		at io.kaitai.struct.JavaMain$.main(JavaMain.scala:239)
		at io.kaitai.struct.JavaMain.main(JavaMain.scala)
	CalcArrayType(UserTypeInstream(List(fmt_oms_apl_full_vdb),None,List())) (of class io.kaitai.struct.datatype.DataType$CalcArrayType)

			  case AnyType => "Object"
			  case KaitaiStreamType => kstreamName
			  case KaitaiStructType | CalcKaitaiStructType => kstructName

			  case t: UserType => types2class(t.name)
			  case EnumType(name, _) => types2class(name)

			  case ArrayType(inType) => s"ArrayList<${kaitaiType2JavaTypeBoxed(inType)}>"

	773:	  case st: SwitchType => kaitaiType2JavaTypeBoxed(st.combinedType)
			}
		  }

I guess `ArrayType` and `CalcArrayType` need to be handled like `KaitaiStructType` and `CalcKaitaiStructType` above, will give it a try...

**Comment by GreyCat** [comment]
Yeah, most likely an issue of mistreating `CalcArrayType` not the same as true arrays.

**Comment by ams-tschoening** [comment]
Found another instance of this problem. The following KSY leads to an error in my currently used version of the compiler, which is some older 0.9, but worked at some points in the past:

      hex_chars:
        value:  |
                ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f']

      as_string:
        value:  hex_chars[(raw[0] & 0xF0) >> 4] + hex_chars[raw[0] & 0x0F] + '-' +
                hex_chars[(raw[1] & 0xF0) >> 4] + hex_chars[raw[1] & 0x0F] + '-' +
                hex_chars[(raw[2] & 0xF0) >> 4] + hex_chars[raw[2] & 0x0F] + '-' +
                hex_chars[(raw[3] & 0xF0) >> 4] + hex_chars[raw[3] & 0x0F] + '-' +
                hex_chars[(raw[4] & 0xF0) >> 4] + hex_chars[raw[4] & 0x0F] + '-' +
                hex_chars[(raw[5] & 0xF0) >> 4] + hex_chars[raw[5] & 0x0F]

The error is the following:

#### fmt_zto_body_v1_mac
    deriveValueType(fmt_zto_body_v1_mac)
    hex_chars derived type: CalcArrayType(CalcStrType)
    Exception in thread "main" io.kaitai.struct.precompile.ErrorInInput: (main): /instances/as_string/value: unable to apply operation [] to CalcArrayType(CalcStrType)
        at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2(ValueTypesDeriver.scala:37)
        at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2$adapted(ValueTypesDeriver.scala:20)
        at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
        at io.kaitai.struct.precompile.ValueTypesDeriver.deriveValueType(ValueTypesDeriver.scala:20)
        at io.kaitai.struct.precompile.ValueTypesDeriver.run(ValueTypesDeriver.scala:12)
        at io.kaitai.struct.precompile.SpecsValueTypeDerive.$anonfun$run$2(SpecsValueTypeDerive.scala:15)
        at io.kaitai.struct.precompile.SpecsValueTypeDerive.$anonfun$run$2$adapted(SpecsValueTypeDerive.scala:13)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
        at io.kaitai.struct.precompile.SpecsValueTypeDerive.run(SpecsValueTypeDerive.scala:13)
        at io.kaitai.struct.Main$.precompile(Main.scala:38)
        at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$3(Main.scala:28)
        at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$3$adapted(Main.scala:27)
        [...]
    Caused by: io.kaitai.struct.precompile.TypeMismatchError: unable to apply operation [] to CalcArrayType(CalcStrType)
        at io.kaitai.struct.translators.TypeDetector.detectTypeRaw(TypeDetector.scala:107)
        at io.kaitai.struct.translators.TypeDetector.detectType(TypeDetector.scala:24)
        at io.kaitai.struct.translators.TypeDetector.detectTypeRaw(TypeDetector.scala:75)
        at io.kaitai.struct.translators.TypeDetector.detectType(TypeDetector.scala:24)
        [...]
        at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2(ValueTypesDeriver.scala:27)
        ... 35 more

**Comment by GreyCat** [comment]
Sorry for taking so long to get into this issue. This is not only something that impacts Java, it probably impacts other languages too?

I'll add a test based on your latest demonstration, and then we can apply your fix to see what languages are impacted.

**Comment by GreyCat** [comment]
At the moment, test revealed that we fail to compile due to:

```
[error] io.kaitai.struct.precompile.ErrorInInput: (main): /instances/double_array_max/value: don't know how to call method 'max' of object type 'CalcArrayType(CalcFloatType)'
```

**Comment by ams-tschoening** [comment]
Would be great if you could have a look at the test I created in the past as well:

https://github.com/kaitai-io/kaitai_struct_tests/pull/51

**Comment by generalmimon** [comment]
I have a question regarding the C++ code generation. I tried to fix the `expr_calc_array_ops` test in C++ and managed to add the missing `vector` import, but now it fails on some type mismatch:

```
expr_calc_array_ops.cpp:195:17: error: cannot convert ‘std::vector<int>’ to ‘std::vector<int>*’ in assignment
```

See [`expr_calc_array_ops.cpp:195`](https://github.com/kaitai-io/ci_targets/blob/107ff6c369a8508b513e30b6f7325c24756ec7e4/compiled/cpp_stl_11/expr_calc_array_ops.cpp#L195) (and [`expr_calc_array_ops.h:164`](https://github.com/kaitai-io/ci_targets/blob/107ff6c369a8508b513e30b6f7325c24756ec7e4/compiled/cpp_stl_11/expr_calc_array_ops.h#L164)) to see the context. I heard that the asterisk `*` means some pointer, but I don't really know what's its purpose and whether it there should be or shouldn't.

Does anybody know?

**Comment by ams-tschoening** [comment]
KS stores some kind of `null`, `undef` etc. in case instance results are not available yet, depending on how a target language implements the concept of references to objects/data. C++ supports that concept with raw pointers (`*`) and objects managing such pointers often called shared pointers or unique pointers or ... The important point is that only references to data can be stored that way, the difference is only who is the owner of the data in the end. You don't need to care about that, but instead need to look at other generated code like the following:

    override def arrayFirst(a: expr): String =
        s"${translate(a)}->front()"

`->` is dereferencing a pointer and wouldn't work without one. Without a pointer one would need to use `.front()` instead. So it seems the generated code using the pointer is OK, even though there's a [runtime config to switch between the possible variants of pointers](https://github.com/kaitai-io/kaitai_struct_compiler/blob/0c02aec204787106d50040a203f52166d84ceca4/shared/src/main/scala/io/kaitai/struct/RuntimeConfig.scala#L26). Looks to me the code creating the vector is missing the details of 1. that a pointer is needed in general and 2. which type of pointer is needed at all:

    s"std::vector<${CppCompiler.kaitaiType2NativeType(config.cppConfig, t)}>" +
        "{" + values.map((value) => translate(value)).mkString(", ") + "}"

vs.

    s"new std::vector<${CppCompiler.kaitaiType2NativeType(config.cppConfig, t)}>" +
        "{" + values.map((value) => translate(value)).mkString(", ") + "}"

Recognize the keyword `new` to create a new instance of some object and returning the pointer to that. What is necessary depends on the runtime config for pointers, like can be seen in [CppCompiler](https://github.com/kaitai-io/kaitai_struct_compiler/blob/0c02aec204787106d50040a203f52166d84ceca4/shared/src/main/scala/io/kaitai/struct/languages/CppCompiler.scala#L709):

        config.cppConfig.pointers match {
          case RawPointers =>
            s"new ${types2class(t.name)}($addParams$io$addArgs)"
          case SharedPointers =>
            s"std::make_shared<${types2class(t.name)}>($addParams$io$addArgs)"
          case UniqueAndRawPointers =>
            importListSrc.addSystem("memory")
            // C++14
            //s"std::make_unique<${types2class(t.name)}>($addParams$io$addArgs)"
            s"std::unique_ptr<${types2class(t.name)}>(new ${types2class(t.name)}($addParams$io$addArgs))"
        }

So to me it looks like your error message is correct, using the pointer is correct and the problem is that `doArrayLiteral` is not properly implemented yet.
