### ISSUE TITLE
Parse error when using parenthesized expression in type argument

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#600]
When I have a type `tree_level` that takes a single argument, I can use it without problems like `tree_level(_index)`. If I write `tree_level((_index))` instead (which should have exactly the same meaning) I get a parse error:

<details>
<summary>Stack trace</summary>

```
Exception in thread "main" io.kaitai.struct.format.YAMLParseException: /types/tree/seq/2: parsing expression '_index)' failed on 1:7, expected "," | CharsWhile(Set( , n)) | "\\\n" | End
        at io.kaitai.struct.format.YAMLParseException$.expression(YAMLParseException.scala:57)
        at io.kaitai.struct.format.AttrSpec$.fromYaml(AttrSpec.scala:163)
        at io.kaitai.struct.format.AttrSpec$.fromYaml(AttrSpec.scala:155)
        at io.kaitai.struct.format.ClassSpec$.$anonfun$seqFromYaml$1(ClassSpec.scala:169)
        at scala.collection.immutable.List.map(List.scala:287)
        at io.kaitai.struct.format.ClassSpec$.seqFromYaml(ClassSpec.scala:168)
        at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:115)
        at io.kaitai.struct.format.ClassSpec$.$anonfun$typesFromYaml$1(ClassSpec.scala:217)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at io.kaitai.struct.format.ClassSpec$.typesFromYaml(ClassSpec.scala:215)
        at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:119)
        at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:240)
        at io.kaitai.struct.formats.JavaKSYParser$.fileNameToSpec(JavaKSYParser.scala:38)
        at io.kaitai.struct.formats.JavaKSYParser$.localFileToSpecs(JavaKSYParser.scala:19)
        at io.kaitai.struct.JavaMain.compileOneInput(JavaMain.scala:275)
        at io.kaitai.struct.JavaMain.$anonfun$run$1(JavaMain.scala:250)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.immutable.List.map(List.scala:295)
        at io.kaitai.struct.JavaMain.run(JavaMain.scala:248)
        at io.kaitai.struct.JavaMain$.main(JavaMain.scala:239)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
```
</details>

**Comment by GreyCat** [comment]
Thanks for this report, @dgelessus! This was indeed a bug in type parenthesis parsing regexp — should be fixed now. [This test](https://github.com/kaitai-io/kaitai_struct_tests/commit/7b0ee006064b0191613257c9517bc823f94ddbb5) should also become green in a short while.
