### ISSUE TITLE
Strange error when I use KSC from JPype

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#608]
JPype is a way call JVM code from python. It is a base of JVM backend for kaitaiStructCompile.py

Unfortunately I have noticed a stange behavior.

When I call `JavaKSYParser.localFileToSpecs`, where `cliCfg.importPaths` is set to something (In my case it is a scala `Seq` with a single str, pointing to the needed dir) and `imports` are used I get a strange error (the notation of stacktrace is the one used in python):

```
Traceback (most recent call last):
  File "List.scala", line 389, in scala.collection.immutable.List.foreach
  File "JavaClassSpecs.scala", line 35, in io.kaitai.struct.formats.JavaClassSpecs.tryAbsolutePaths
  File "JavaClassSpecs.scala", line 31, in io.kaitai.struct.formats.JavaClassSpecs.$anonfun$importAbsolute$3
  File "JavaClassSpecs.scala", line 71, in io.kaitai.struct.formats.JavaClassSpecs$.cached
  File "JavaClassSpecs.scala", line 31, in io.kaitai.struct.formats.JavaClassSpecs.$anonfun$importAbsolute$1
  File "Future.scala", line 655, in scala.concurrent.Future$.$anonfun$apply$1
  File "Try.scala", line 251, in scala.util.Success.$anonfun$map$1
  File "Try.scala", line 209, in scala.util.Success.map
  File "Future.scala", line 289, in scala.concurrent.Future.$anonfun$map$1
  File "Promise.scala", line 29, in scala.concurrent.impl.Promise.liftedTree1$1
  File "Promise.scala", line 29, in scala.concurrent.impl.Promise.$anonfun$transform$1
  File "Promise.scala", line 60, in scala.concurrent.impl.CallbackRunnable.run
  File "ExecutionContextImpl.scala", line 140, in scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec
  File "None", line -1, in java.util.concurrent.ForkJoinTask.doExec
  File "None", line -1, in java.util.concurrent.ForkJoinPool$WorkQueue.runTask
  File "None", line -1, in java.util.concurrent.ForkJoinPool.runWorker
  File "None", line -1, in java.util.concurrent.ForkJoinWorkerThread.run
jpype._jclass.java.lang.ClassCastException: java.lang.ClassCastException: scala.collection.convert.Wrappers$IterableWrapper cannot be cast to java.lang.String

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "JavaClassSpecs.scala", line 75, in io.kaitai.struct.formats.JavaClassSpecs$.cached
  File "JavaClassSpecs.scala", line 31, in io.kaitai.struct.formats.JavaClassSpecs.$anonfun$importAbsolute$1
  File "Future.scala", line 655, in scala.concurrent.Future$.$anonfun$apply$1
  File "Try.scala", line 251, in scala.util.Success.$anonfun$map$1
  File "Try.scala", line 209, in scala.util.Success.map
  File "Future.scala", line 289, in scala.concurrent.Future.$anonfun$map$1
  File "Promise.scala", line 29, in scala.concurrent.impl.Promise.liftedTree1$1
  File "Promise.scala", line 29, in scala.concurrent.impl.Promise.$anonfun$transform$1
  File "Promise.scala", line 60, in scala.concurrent.impl.CallbackRunnable.run
  File "ExecutionContextImpl.scala", line 140, in scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec
  File "None", line -1, in java.util.concurrent.ForkJoinTask.doExec
  File "None", line -1, in java.util.concurrent.ForkJoinPool$WorkQueue.runTask
  File "None", line -1, in java.util.concurrent.ForkJoinPool.runWorker
  File "None", line -1, in java.util.concurrent.ForkJoinWorkerThread.run
jpype._jclass.io.kaitai.struct.precompile.ErrorInInput: io.kaitai.struct.precompile.ErrorInInput: nt_mdt: /meta/imports/0: scala.collection.convert.Wrappers$IterableWrapper cannot
be cast to java.lang.String
```

The imports used in a ksy were:
```yaml
  imports:
    - /common/ieee754_float/f10le
    - ./nt_mdt_color_table
```

Any ideas why do I get the error?

**Comment by GreyCat** [comment]
The only thing I can probably suggest is following up with JPype project, as it looks like it's doing something weird with futures/promises implementation. Unfortunately, to cope with JS async file accessing implementation, we had to use common middle ground of futures/promises-based API for accessing importing files everything, include JVM implementation. Looks like it's behaving not the way it's intended to in JPype.
