### ISSUE TITLE
Buffer Underflow Exception in Java Example 

### ISSUE THREAD

**Issue by nsoft** [kaitai-io/kaitai_struct#612]
Using the code found here: https://formats.kaitai.io/stl/java.html
And the dependency found here:https://doc.kaitai.io/lang_java.html

Trying to read a binary STL file (that opens in meshlab just fine) hits this:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.simontuffs.onejar.Boot.run(Boot.java:351)
        at com.simontuffs.onejar.Boot.main(Boot.java:156)
Caused by: java.nio.BufferUnderflowException
        at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:647)
        at java.base/java.nio.DirectByteBuffer.getFloat(DirectByteBuffer.java:951)
        at io.kaitai.struct.ByteBufferKaitaiStream.readF4le(ByteBufferKaitaiStream.java:251)
        at com.foo.stl.Stl$Vec3d._read(Stl.java:107)
        at com.foo.stl.Stl$Vec3d.<init>(Stl.java:102)
        at com.foo.stl.Stl$Triangle._read(Stl.java:73)
        at com.foo.stl.Stl$Triangle.<init>(Stl.java:67)
        at com.foo.stl.Stl._read(Stl.java:41)
        at com.foo.stl.Stl.<init>(Stl.java:34)
        at com.foo.stl.Stl.<init>(Stl.java:23)
        at com.foo.stl.Stl.fromFile(Stl.java:19)
        at com.foo.stl.Converter.main(Converter.java:55)
        ... 6 more
```
If there's some other process necessary, to use the code from your page let me know. Note that I really just want something that reads STL into java, I'm not interested in tweaking parsers to do custom things (at least for now). 

Can reproduce with this: https://github.com/dillonhuff/stl_parser/blob/master/Box1x1x1.stl or any other STL file I've tried.

That trace was on Java 11 - 
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

I got similar results for jdk 8
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

FWIW, I know this isn't a java-centric project, but it would be nice if your dependency jar included the working copies of the generated java classes for your various formats in addition to the base classes.

**Comment by gus-asf** [comment]
Hand created this test file (text format)
```
solid cube
  facet normal 0.000000e+00 0.000000e+00 -1.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 0.000000e+00
      vertex 0.000000e+00 1.000000e+00 0.000000e+00
      vertex 1.000000e+00 1.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 0.000000e+00 -1.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 0.000000e+00
      vertex 1.000000e+00 1.000000e+00 0.000000e+00
      vertex 1.000000e+00 0.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 0.000000e+00 -1.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 1.000000e+00
      vertex 1.000000e+00 1.000000e+00 1.000000e+00
      vertex 0.000000e+00 1.000000e+00 1.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 0.000000e+00 -1.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 1.000000e+00
      vertex 1.000000e+00 0.000000e+00 1.000000e+00
      vertex 1.000000e+00 1.000000e+00 1.000000e+00
    endloop
  endfacet
  facet normal 1.000000e+00 0.000000e+00 0.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 1.000000e+00
      vertex 0.000000e+00 1.000000e+00 1.000000e+00
      vertex 0.000000e+00 1.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal -1.000000e+00 0.000000e+00 0.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 1.000000e+00
      vertex 0.000000e+00 1.000000e+00 0.000000e+00
      vertex 0.000000e+00 0.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal 1.000000e+00 0.000000e+00 0.000000e+00
    outer loop
      vertex 1.000000e+00 0.000000e+00 1.000000e+00
      vertex 1.000000e+00 1.000000e+00 0.000000e+00
      vertex 1.000000e+00 1.000000e+00 1.000000e+00
    endloop
  endfacet
  facet normal 1.000000e+00 0.000000e+00 0.000000e+00
    outer loop
      vertex 1.000000e+00 0.000000e+00 1.000000e+00
      vertex 1.000000e+00 0.000000e+00 0.000000e+00
      vertex 1.000000e+00 1.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 -1.000000e+00 0.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 1.000000e+00
      vertex 1.000000e+00 0.000000e+00 0.000000e+00
      vertex 1.000000e+00 0.000000e+00 1.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 -1.000000e+00 0.000000e+00
    outer loop
      vertex 0.000000e+00 0.000000e+00 1.000000e+00
      vertex 0.000000e+00 0.000000e+00 0.000000e+00
      vertex 1.000000e+00 0.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 1.000000e+00 0.000000e+00
    outer loop
      vertex 0.000000e+00 1.000000e+00 1.000000e+00
      vertex 1.000000e+00 1.000000e+00 1.000000e+00
      vertex 1.000000e+00 1.000000e+00 0.000000e+00
    endloop
  endfacet
  facet normal 0.000000e+00 1.000000e+00 0.000000e+00
    outer loop
      vertex 0.000000e+00 1.000000e+00 1.000000e+00
      vertex 1.000000e+00 1.000000e+00 0.000000e+00
      vertex 0.000000e+00 1.000000e+00 0.000000e+00
    endloop
  endfacet
endsolid cube
```
Opened it in mesh lab, turned on show normals and axis to verify it made sense, saved it as binary,

Edited the _read() method like this:
```
    private void _read() {
      this.x = this._io.readF4le();
      System.out.println("read x:" + this.x);
      this.y = this._io.readF4le();
      System.out.println("read y:" + this.y);
      this.z = this._io.readF4le();
      System.out.println("read z:" + this.z);
      this.abr = this._io.readU2le();
      System.out.println("read a:" + this.abr);
    }
```
tried to parse the binary version of the above STL and got:
```
read x:0.0
read y:0.0
read z:-1.0
read a:0
read x:0.0
read y:0.0
read z:0.0
read a:0
read x:1.0
read y:0.0
read z:1.0
read a:0
read x:2.278E-41
read y:0.0
read z:0.0
read a:0
read x:0.0
read y:6.8697E-41
read z:0.0
read a:0
read x:0.0
read y:1.0
read z:1.0
read a:0
read x:0.0
read y:2.278E-41
read z:0.0
read a:0
read x:0.0
read y:0.0
read z:0.0
read a:16256
read x:0.0
read y:0.0
read z:1.0
read a:0
read x:2.278E-41
read y:2.278E-41
read z:2.278E-41
read a:0
read x:1.0
read y:1.0
read z:0.0
read a:0
read x:0.0
read y:1.0
read z:0.0
read a:0
read x:0.0
read y:2.278E-41
read z:2.278E-41
read a:0
read x:1.0
read y:1.0
read z:1.0
read a:0
read x:2.278E-41
read y:-1.0
read z:0.0
read a:0
read x:0.0
read y:0.0
read z:0.0
read a:16256
read x:0.0
read y:1.0
read z:1.0
read a:0
read x:0.0
read y:2.278E-41
read z:0.0
read a:0
read x:6.8697E-41
read y:0.0
read z:0.0
read a:0
read x:0.0
read y:1.0
read z:0.0
read a:0
read x:2.278E-41
read y:0.0
read z:0.0
read a:0
read x:0.0
read y:0.0
read z:2.278E-41
read a:32768
read x:0.0
read y:1.0
read z:0.0
read a:0
read x:2.278E-41
read y:2.278E-41
read z:2.278E-41
read a:0
read x:1.0
read y:1.0
read z:1.0
read a:0
read x:1.0
read y:0.0
read z:0.0
read a:0
read x:2.278E-41
read y:0.0
read z:2.278E-41
read a:16256
read x:0.0
read y:0.0
read z:1.0
read a:0
read x:2.278E-41
read y:0.0
read z:0.0
read a:0
read x:6.8697E-41
read y:0.0
read z:0.0
read a:0
read x:1.0
read y:1.0
read z:0.0
read a:0
read x:0.0
read y:2.278E-41
read z:0.0
read a:16256
read x:0.0
read y:0.0
read z:6.8697E-41
read a:0
read x:0.0
read y:0.0
read z:1.0
read a:0
read x:0.0
read y:0.0
read z:0.0
read a:16256
read x:0.0
read y:0.0
read z:0.0
read a:32768
read x:1.0
read y:0.0
read z:0.0
read a:0
read x:2.278E-41
read y:2.278E-41
read z:2.278E-41
read a:16256
read x:1.0
read y:1.0
read z:1.0
read a:0
read x:0.0
read y:0.0
read z:1.0
read a:0
read x:0.0
read y:0.0
read z:2.278E-41
read a:16256
read x:1.0
read y:1.0
read z:0.0
read a:0
read x:0.0
read y:2.278E-41
read z:0.0
Exception in thread "main" java.lang.reflect.InvocationTargetException... etc
```

**Comment by nsoft** [comment]
My hand written hand STL had a couple of normal vectors with inverted sign, but at least when I saved as text, meshlab corrected that... I noticed that meshlab prefers the direction of the points vs the normal vector. Fixing that changed nothing about the exported binary (based on diff of xxd output). Oddly it also wrote -0.000000e+00 twice also, both times in normal vectors. I think the problem is that you're reading the abr for every Vect3D when it should only be read once a triangle... here's the hex of the binary file for reference, but compare

https://formats.kaitai.io/stl/index.html 
vs
https://www.fabbers.com/tech/STL_Format

The latter specifies Attribute Byte Count as occuring once per triangle (which is also consistent with the binary below produced by meshlab)
```
00000000: 5643 4720 2020 2020 2020 2020 2020 2020  VCG             
00000010: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000020: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000030: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000040: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000050: 0c00 0000 0000 0000 0000 0000 0000 80bf  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 803f 0000 0000 0000 803f 0000 803f  ...?.......?...?
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 80bf 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 803f 0000 803f 0000 0000 0000 803f 0000  .?...?.......?..
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 803f 0000 0000 0000 0000 0000 803f  ...?...........?
000000d0: 0000 803f 0000 803f 0000 803f 0000 0000  ...?...?...?....
000000e0: 0000 803f 0000 803f 0000 0000 0000 0000  ...?...?........
000000f0: 0000 0000 803f 0000 0000 0000 0000 0000  .....?..........
00000100: 803f 0000 803f 0000 0000 0000 803f 0000  .?...?.......?..
00000110: 803f 0000 803f 0000 803f 0000 0000 80bf  .?...?...?......
00000120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000130: 0000 803f 0000 0000 0000 803f 0000 803f  ...?.......?...?
00000140: 0000 0000 0000 803f 0000 0000 0000 0000  .......?........
00000150: 80bf 0000 0000 0000 0000 0000 0000 0000  ................
00000160: 0000 0000 803f 0000 0000 0000 803f 0000  .....?.......?..
00000170: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000180: 0000 803f 0000 0080 0000 0000 0000 803f  ...?...........?
00000190: 0000 0000 0000 803f 0000 803f 0000 803f  .......?...?...?
000001a0: 0000 0000 0000 803f 0000 803f 0000 803f  .......?...?...?
000001b0: 0000 0000 803f 0000 0000 0000 0000 0000  .....?..........
000001c0: 803f 0000 0000 0000 803f 0000 803f 0000  .?.......?...?..
000001d0: 0000 0000 0000 0000 803f 0000 803f 0000  .........?...?..
000001e0: 0000 0000 0000 0000 0000 80bf 0000 0000  ................
000001f0: 0000 0000 0000 0000 0000 803f 0000 803f  ...........?...?
00000200: 0000 0000 0000 0000 0000 803f 0000 0000  ...........?....
00000210: 0000 803f 0000 0000 0000 0000 80bf 0000  ...?............
00000220: 0000 0000 0000 0000 0000 0000 803f 0000  .............?..
00000230: 0000 0000 0000 0000 0000 0000 803f 0000  .............?..
00000240: 0000 0000 0000 0000 0000 0080 0000 803f  ...............?
00000250: 0000 0000 0000 0000 0000 803f 0000 803f  ...........?...?
00000260: 0000 803f 0000 803f 0000 803f 0000 803f  ...?...?...?...?
00000270: 0000 803f 0000 0000 0000 0000 0000 0000  ...?............
00000280: 803f 0000 0000 0000 0000 0000 803f 0000  .?...........?..
00000290: 803f 0000 803f 0000 803f 0000 0000 0000  .?...?...?......
000002a0: 0000 0000 803f 0000 0000 0000            .....?......
```

**Comment by nsoft** [comment]
This appears to have been introduced in #554

**Comment by generalmimon** [comment]
I believe this issue has been fixed by merging https://github.com/kaitai-io/kaitai_struct_formats/pull/217 - closing.
