### ISSUE TITLE
NoSuchElementException: None.get when compiling .ksy with types

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#663]
I tryed to play with Java API to create visualizer. When I try to compile such `.ksy`, it succesfully compiled:
```yaml
meta:
  id: test
seq:
  - id: mac
    size: 8
```
But when I add `types` entry, even unused, it ends with exception:
```yaml
meta:
  id: test
seq:
  - id: mac
    size: 8
types:
  value:
    seq:
      - id: data
        size: 8
```

```
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at io.kaitai.struct.datatype.DataType$UserType.isOpaque(DataType.scala:99)
	at io.kaitai.struct.TypeProcessor$.getOpaqueDataTypes(TypeProcessor.scala:34)
	at io.kaitai.struct.TypeProcessor$$anonfun$getOpaqueClasses$1.apply(TypeProcessor.scala:13)
	at io.kaitai.struct.TypeProcessor$$anonfun$getOpaqueClasses$1.apply(TypeProcessor.scala:12)
	at scala.collection.immutable.List.map(List.scala:284)
	at io.kaitai.struct.TypeProcessor$.getOpaqueClasses(TypeProcessor.scala:12)
	at io.kaitai.struct.ClassCompiler.compileOpaqueClasses(ClassCompiler.scala:35)
	at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:24)
	at io.kaitai.struct.visualizer.VisualizerPanel.compileKSY(VisualizerPanel.java:100)
	at io.kaitai.struct.visualizer.VisualizerPanel.parseFileWithKSY(VisualizerPanel.java:121)
	at io.kaitai.struct.visualizer.VisualizerPanel.loadAll(VisualizerPanel.java:61)
	at io.kaitai.struct.visualizer.MainWindow.main(MainWindow.java:24)
```

I use code from https://github.com/kaitai-io/kaitai_struct_gui/pull/6 to compile `.ksy`

**Comment by Mingun** [comment]
Actually, this and similar errors was due to that I do not call `Main.precompile` and `ClassSpec` doesn't have some required data.
