### ISSUE TITLE
Internal compiler error: scala.MatchError: b1

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#684]
> Also, most errors are very obscure

One of such errors. When trying to parse such `ksy`:
```yaml
meta:
  id: bug
params:
  - id: param
    type: b1
seq: []
```
compiler throws error
```
Exception in thread "main" scala.MatchError: b1 (of class java.lang.String)
	at io.kaitai.struct.datatype.DataType$.pureFromString(DataType.scala:322)
	at io.kaitai.struct.format.ParamDefSpec$.fromYaml(ParamDefSpec.scala:32)
	at io.kaitai.struct.format.ParamDefSpec$.fromYaml(ParamDefSpec.scala:19)
	at io.kaitai.struct.format.ClassSpec$$anonfun$3.apply(ClassSpec.scala:140)
	at io.kaitai.struct.format.ClassSpec$$anonfun$3.apply(ClassSpec.scala:139)
	at scala.collection.immutable.List.map(List.scala:284)
	at io.kaitai.struct.format.ClassSpec$.paramDefFromYaml(ClassSpec.scala:139)
	at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:95)
	at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:224)
	at io.kaitai.struct.formats.JavaKSYParser$.fileNameToSpec(JavaKSYParser.scala:29)
	at io.kaitai.struct.formats.JavaKSYParser.fileNameToSpec(JavaKSYParser.scala)
	at io.kaitai.struct.visualizer.VisualizerPanel.compileKSY(VisualizerPanel.java:89)
	at io.kaitai.struct.visualizer.VisualizerPanel.parseFileWithKSY(VisualizerPanel.java:125)
	at io.kaitai.struct.visualizer.VisualizerPanel.loadAll(VisualizerPanel.java:67)
	at io.kaitai.struct.visualizer.MainWindow.main(MainWindow.java:24)
```

_Originally posted by @Mingun in https://github.com/kaitai-io/kaitai_struct/issues/669#issuecomment-573429535_

**Comment by generalmimon** [comment]
I can reproduce this only in the stable web IDE, in the devel web IDE this works already fine. So this issue isn't relevant anymore.
