### ISSUE TITLE
risk of circular import when using custom processing routines on python

### ISSUE THREAD

**Issue by joeyoravec** [kaitai-io/kaitai_struct#691]
When using a custom processing routine with python like:
```
seq:
  - id: empty
    size: 4
    process: test_process
```
ksc will generate `testcase_a.py` with a `from test_process import TestProcess` at the top of the file, expecting to have a processing routine like:
```python
class TestProcess(object):
        def decode(self, bytes_in):
                return bytes_in
```

If this routine needs to access anything, like a KS defined enumeration, then the developer is likely to add an import line:
```python
from testcase_a import TestcaseA
```
which leads to a circular import ([link](https://stackabuse.com/python-circular-imports/)), and an error message like:
```
Traceback (most recent call last):
  File "./py-testcase.py", line 4, in <module>
    from testcase_a import TestcaseA
  File "/home/joravec4/py-testcase/testcase_a.py", line 6, in <module>
    from test_process import TestProcess
  File "/home/joravec4/py-testcase/test_process.py", line 2, in <module>
    from testcase_a import TestcaseA
ImportError: cannot import name 'TestcaseA'
```

**Comment by joeyoravec** [comment]
github won't let me attach the code. See the code to reproduce:

testcase_a.ksy:
```
meta:
  id: testcase_a

seq:
  - id: empty
    size: 4
    process: test_process

enums:
  test_enum:
    0: val_a
    1: val_b
```

py-testcase.py
```python
#!/usr/bin/python3

from kaitaistruct import KaitaiStream, BytesIO
from testcase_a import TestcaseA

def main():
        stream = KaitaiStream(BytesIO(b"abcd"))
        obj = TestcaseA(stream)

if __name__ == "__main__":
        main()
```

test_process.py:
```
# BUG: This line causes a circular import
from testcase_a import TestcaseA

class TestProcess(object):
        def decode(self, bytes_in):
                # Moving the line here is a possible workaround
                #from testcase_a import TestcaseA

                # As a user, I want to use testcaseA.TestEnum.valA
                print(TestcaseA.TestEnum.val_a)

                return bytes_in
```

Reproduction with `ksc` 0.8:
```
$ ksc testcase_a.ksc -t python
$ ./py-testcase.py
Traceback (most recent call last):
  File "./py-testcase.py", line 4, in <module>
    from testcase_a import TestcaseA
  File "/home/joravec4/py-testcase/testcase_a.py", line 6, in <module>
    from test_process import TestProcess
  File "/home/joravec4/py-testcase/test_process.py", line 2, in <module>
    from testcase_a import TestcaseA
ImportError: cannot import name 'TestcaseA'
```

I was able to workaround (as recommended: [link](https://stackabuse.com/python-circular-imports/)) by doing the `import` in the body of the `decode()`, instead of global scope / immediate.

I don't think that a KS code change is required. I think the "fix" might be to provide an example in the KS documentation, because the design-pattern was not very obvious.

**Comment by joeyoravec** [comment]
This issue is similar to #235, #337 but I think it's different

#337 with kaitai-io/kaitai_struct_compiler@c5639b7 changed a `from xx import yy` to `import zz` as a workaround
```
-    out.puts(s"from $prefix$name import ${type2class(name)}")
+    out.puts(s"import $opaquePrefix$name")
```

I think this testcase hits a different area of the code where [PythonCompiler.scala#L209](https://github.com/kaitai-io/kaitai_struct_compiler/blob/0a81c0173007c9c997fc5fc9192ebb9c60c5ea82/shared/src/main/scala/io/kaitai/struct/languages/PythonCompiler.scala#L209) generates the `from xx import yy`:
```
      case ProcessCustom(name, args) =>
        val procClass = if (name.length == 1) {
          val onlyName = name.head
          val className = type2class(onlyName)
          importList.add(s"from $onlyName import $className")
          className
        } else {
          val pkgName = name.init.mkString(".")
          importList.add(s"import $pkgName")
          s"$pkgName.${type2class(name.last)}"
        }
```

so this testcase is different, and unaffected by the changes in #337.

No idea if a similar change would be appropriate. As stated above, my current workaround is to defer `import` until the `decode()` function 

For completeness, as requested, I used `kaitai-struct-compiler 0.9-SNAPSHOT20200122.115442.05b537e9` to confirm that `ksc` still generates `from testcase_a import TestcaseA` at the top of the file with this testcase.
