### ISSUE TITLE
Array of byte arrays from an expression and from stream have incompatible types

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#719]
An array of byte arrays created in an expression (e. g. `[[0x00, 0x00], [0x11, 0x11]]`) seems to be type-incompatible with an array of byte arrays read from a stream (using `size` and `repeat`). Minimal repro code:

```yaml
meta:
  id: repro
seq:
  - id: reserved
    type: b7
  - id: use_custom_table
    type: b1
  - id: custom_table
    size: 2
    repeat: expr
    repeat-expr: 4
    if: use_custom_table
  - id: data
    size-eos: true
instances:
  default_table:
    value: |
      [[0x00, 0x00], [0x11, 0x11], [0x22, 0x22], [0x33, 0x33]]
  table:
    value: |
      use_custom_table ? custom_table : default_table
```

Compiling this (compiler revision kaitai-io/kaitai_struct_compiler@8469ee26b59d02a9054132ef404e8bc931c421bb) gives me the error `(main): /instances/table/value: can't combine output types: ArrayTypeInStream(BytesLimitType(IntNum(2),None,false,None,None)) vs CalcArrayType(CalcBytesType)`.

<details>
<summary>Full verbose output</summary>

```
[IJ]sbt:root> compilerJVM/run --ksc-exceptions --verbose all --target python --python-package "." repro.ksy
[info] Running io.kaitai.struct.JavaMain --ksc-exceptions --verbose all --target python --python-package . repro.ksy
home path: location = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-24/target/c44142db/kaitai-struct-compiler_2.12-0.9-SNAPSHOT.jar
... URL-decoded = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-24/target/c44142db/kaitai-struct-compiler_2.12-0.9-SNAPSHOT.jar
... home = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-24/target
... formats = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-24/target/formats
... home formats dir doesn't exist => fail
parsing repro.ksy...
reading repro.ksy...
.. LoadImports: processing class repro (workDir = RelativeImportPath(List()))
imports done, got: Set(repro) (async=List())
markupParentTypes(repro)
... seq
... instances
### SpecsValueTypeDerive: iteration #1
#### repro
deriveValueType(repro)
default_table derived type: CalcArrayType(CalcBytesType)
[error] (run-main-17) io.kaitai.struct.precompile.ErrorInInput: (main): /instances/table/value: can't combine output types: ArrayTypeInStream(BytesLimitType(IntNum(2),None,false,None,None)) vs CalcArrayType(CalcBytesType)
[error] io.kaitai.struct.precompile.ErrorInInput: (main): /instances/table/value: can't combine output types: ArrayTypeInStream(BytesLimitType(IntNum(2),None,false,None,None)) vs CalcArrayType(CalcBytesType)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2(ValueTypesDeriver.scala:37)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2$adapted(ValueTypesDeriver.scala:20)
[error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.deriveValueType(ValueTypesDeriver.scala:20)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.run(ValueTypesDeriver.scala:12)
[error] 	at io.kaitai.struct.precompile.SpecsValueTypeDerive.$anonfun$run$2(SpecsValueTypeDerive.scala:15)
[error] 	at io.kaitai.struct.precompile.SpecsValueTypeDerive.$anonfun$run$2$adapted(SpecsValueTypeDerive.scala:13)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at io.kaitai.struct.precompile.SpecsValueTypeDerive.run(SpecsValueTypeDerive.scala:13)
[error] 	at io.kaitai.struct.Main$.precompile(Main.scala:58)
[error] 	at io.kaitai.struct.Main$.$anonfun$precompile$1(Main.scala:40)
[error] 	at io.kaitai.struct.Main$.$anonfun$precompile$1$adapted(Main.scala:39)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at io.kaitai.struct.Main$.precompile(Main.scala:39)
[error] 	at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$1(Main.scala:27)
[error] 	at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$1$adapted(Main.scala:24)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
[error] 	at scala.util.Success.map(Try.scala:209)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Caused by: io.kaitai.struct.precompile.TypeMismatchError: can't combine output types: ArrayTypeInStream(BytesLimitType(IntNum(2),None,false,None,None)) vs CalcArrayType(CalcBytesType)
[error] 	at io.kaitai.struct.translators.TypeDetector$.combineTypesAndFail(TypeDetector.scala:419)
[error] 	at io.kaitai.struct.translators.TypeDetector.detectTypeRaw(TypeDetector.scala:98)
[error] 	at io.kaitai.struct.translators.TypeDetector.detectType(TypeDetector.scala:25)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2(ValueTypesDeriver.scala:27)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.$anonfun$deriveValueType$2$adapted(ValueTypesDeriver.scala:20)
[error] 	at scala.collection.immutable.Map$Map2.foreach(Map.scala:146)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.deriveValueType(ValueTypesDeriver.scala:20)
[error] 	at io.kaitai.struct.precompile.ValueTypesDeriver.run(ValueTypesDeriver.scala:12)
[error] 	at io.kaitai.struct.precompile.SpecsValueTypeDerive.$anonfun$run$2(SpecsValueTypeDerive.scala:15)
[error] 	at io.kaitai.struct.precompile.SpecsValueTypeDerive.$anonfun$run$2$adapted(SpecsValueTypeDerive.scala:13)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at io.kaitai.struct.precompile.SpecsValueTypeDerive.run(SpecsValueTypeDerive.scala:13)
[error] 	at io.kaitai.struct.Main$.precompile(Main.scala:58)
[error] 	at io.kaitai.struct.Main$.$anonfun$precompile$1(Main.scala:40)
[error] 	at io.kaitai.struct.Main$.$anonfun$precompile$1$adapted(Main.scala:39)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at io.kaitai.struct.Main$.precompile(Main.scala:39)
[error] 	at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$1(Main.scala:27)
[error] 	at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$1$adapted(Main.scala:24)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
[error] 	at scala.util.Success.map(Try.scala:209)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Nonzero exit code: 1
[error] (compilerJVM / Compile / run) Nonzero exit code: 1
```
</details>

Background: I'm writing a spec for a compression format that uses a simple lookup table/dictionary for compression. The lookup table is either stored in the file, or a fixed default lookup table is used. I wanted to implement this in the spec with a `value` instance that uses a conditional expression to select either the lookup table from the file or the hardcoded one. This is currently not possible because of this issue.

**Comment by cherue** [comment]
I think this applies to simple byte arrays, too. I ran into this with `bytesToStr` in JS, where expression array bytes are treated as an array of numbers instead. While looking into it I figured it has something to do with `doByteArrayLiteral` and `doByteArrayNonLiteral`. Some targets have both of them defined, some don't. JS only has one of them (maybe it should have both?).

Ping @GreyCat

**Comment by generalmimon** [comment]
@dgelessus Should be working now. The particular case you describe is covered in test [`CombineBytes`](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/combine_bytes.ksy). It just combines the different byte array types with the conditional (ternary) operator instead of using array literals, but combining types of `?:` operands and of the individual elements of the array literals is ultimately done with the same function, so it should work for arrays as well.

@cherue 
> I ran into this with `bytesToStr` in JS, where expression array bytes are treated as an array of numbers instead.

Yeah, I can confirm this behavior (I've added test [`ExprBytesLiteral`](https://github.com/kaitai-io/kaitai_struct_tests/commit/ed03b4d8e33090833c6d67a1beb3939baf4dc6e0) to demonstrate that) , but it's a different issue. The types are combined properly, but the translator doesn't know how to translate it. It seems that there is some possibility to handle even the [byte array](https://github.com/kaitai-io/kaitai_struct_compiler/blob/2333448059e4887701102177420cd36e7b322ee3/shared/src/main/scala/io/kaitai/struct/translators/CommonArraysAndCast.scala#L85)  involving expressions, but the method `doByteArray` is called only if the [casting `.as<bytes>`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/2333448059e4887701102177420cd36e7b322ee3/shared/src/main/scala/io/kaitai/struct/translators/CommonArraysAndCast.scala#L62) is present after the literal. So

```yaml
meta:
  id: expr_bytes_literal
seq:
  - id: one
    type: s1
  - id: two
    type: s1
instances:
  literal:
    value: '[one, two].as<bytes>'
```

should probably work (but I can't check it, I'm typing from my mobile). _"bytes" means [`CalcBytesType`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/2333448059e4887701102177420cd36e7b322ee3/shared/src/main/scala/io/kaitai/struct/datatype/DataType.scala#L404)._

**Comment by dgelessus** [comment]
Can confirm that it's working now in my use case. Thank you for the quick fix @generalmimon!

**Comment by cherue** [comment]
@generalmimon Does that mean `bytesToStr` should accept `number[]` and just cast it?
