### ISSUE TITLE
_sizeof does not work on array fields

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct#721]
Minimal repro code:

```yaml
meta:
  id: repro
seq:
  - id: num_things
    type: u1
  - id: things
    type: u1
    repeat: expr
    repeat-expr: num_things
instances:
  sizeof_things:
    value: things._sizeof
```

Compiling this (compiler version kaitai-io/kaitai_struct_compiler@8469ee26b59d02a9054132ef404e8bc931c421bb) gives me the error `ArrayTypeInStream(Int1Type(false)) (of class io.kaitai.struct.datatype.DataType$ArrayTypeInStream)`.

<details>
<summary>Full verbose output</summary>

```
[IJ]sbt:root> compilerJVM/run --ksc-exceptions --verbose all --target python --python-package "." repro.ksy
[info] Running io.kaitai.struct.JavaMain --ksc-exceptions --verbose all --target python --python-package . repro.ksy
home path: location = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-32/target/c44142db/kaitai-struct-compiler_2.12-0.9-SNAPSHOT.jar
... URL-decoded = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-32/target/c44142db/kaitai-struct-compiler_2.12-0.9-SNAPSHOT.jar
... home = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-32/target
... formats = /var/folders/gb/hvb6c1ln4636s5nzqr56lplm0000gn/T/sbt_21cac57/job-32/target/formats
... home formats dir doesn't exist => fail
parsing repro.ksy...
reading repro.ksy...
.. LoadImports: processing class repro (workDir = RelativeImportPath(List()))
imports done, got: Set(repro) (async=List())
markupParentTypes(repro)
... seq
... instances
### SpecsValueTypeDerive: iteration #1
#### repro
deriveValueType(repro)
sizeof_things derived type: CalcIntType
.... => changed
### SpecsValueTypeDerive: iteration #2
#### repro
deriveValueType(repro)
.... => no changes
## value type deriving finished in 2 iteration(s)
sizeof(repro) = DynamicSized
validating top level class 'repro'
validateClass(repro)
validateAttr(num_things)
validateAttr(things)
[error] (run-main-1f) scala.MatchError: ArrayTypeInStream(Int1Type(false)) (of class io.kaitai.struct.datatype.DataType$ArrayTypeInStream)
[error] scala.MatchError: ArrayTypeInStream(Int1Type(false)) (of class io.kaitai.struct.datatype.DataType$ArrayTypeInStream)
[error] 	at io.kaitai.struct.precompile.CalculateSeqSizes$.dataTypeByteSize(CalculateSeqSizes.scala:116)
[error] 	at io.kaitai.struct.precompile.CalculateSeqSizes$.dataTypeBitsSize(CalculateSeqSizes.scala:90)
[error] 	at io.kaitai.struct.translators.CommonSizeOf$.getBitsSizeOfType(CommonSizeOf.scala:19)
[error] 	at io.kaitai.struct.translators.ExpressionValidator.byteSizeOfValue(ExpressionValidator.scala:129)
[error] 	at io.kaitai.struct.translators.ExpressionValidator.byteSizeOfValue(ExpressionValidator.scala:18)
[error] 	at io.kaitai.struct.translators.CommonMethods.translateAttribute(CommonMethods.scala:24)
[error] 	at io.kaitai.struct.translators.CommonMethods.translateAttribute$(CommonMethods.scala:17)
[error] 	at io.kaitai.struct.translators.ExpressionValidator.translateAttribute(ExpressionValidator.scala:18)
[error] 	at io.kaitai.struct.translators.ExpressionValidator.validate(ExpressionValidator.scala:62)
[error] 	at io.kaitai.struct.precompile.TypeValidator.validateValueInstance(TypeValidator.scala:101)
[error] 	at io.kaitai.struct.precompile.TypeValidator.$anonfun$validateClass$3(TypeValidator.scala:51)
[error] 	at io.kaitai.struct.precompile.TypeValidator.$anonfun$validateClass$3$adapted(TypeValidator.scala:46)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:120)
[error] 	at io.kaitai.struct.precompile.TypeValidator.validateClass(TypeValidator.scala:46)
[error] 	at io.kaitai.struct.precompile.TypeValidator.$anonfun$run$3(TypeValidator.scala:29)
[error] 	at io.kaitai.struct.precompile.TypeValidator.$anonfun$run$3$adapted(TypeValidator.scala:29)
[error] 	at io.kaitai.struct.format.ClassSpec.forEachRec(ClassSpec.scala:75)
[error] 	at io.kaitai.struct.precompile.TypeValidator.$anonfun$run$1(TypeValidator.scala:29)
[error] 	at io.kaitai.struct.precompile.TypeValidator.$anonfun$run$1$adapted(TypeValidator.scala:26)
[error] 	at io.kaitai.struct.format.ClassSpecs.$anonfun$forEachTopLevel$1(ClassSpecs.scala:31)
[error] 	at io.kaitai.struct.format.ClassSpecs.$anonfun$forEachTopLevel$1$adapted(ClassSpecs.scala:29)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at io.kaitai.struct.format.ClassSpecs.forEachTopLevel(ClassSpecs.scala:29)
[error] 	at io.kaitai.struct.precompile.TypeValidator.run(TypeValidator.scala:26)
[error] 	at io.kaitai.struct.Main$.precompile(Main.scala:60)
[error] 	at io.kaitai.struct.Main$.$anonfun$precompile$1(Main.scala:40)
[error] 	at io.kaitai.struct.Main$.$anonfun$precompile$1$adapted(Main.scala:39)
[error] 	at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:138)
[error] 	at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:236)
[error] 	at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:229)
[error] 	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
[error] 	at scala.collection.mutable.HashMap.foreach(HashMap.scala:138)
[error] 	at io.kaitai.struct.Main$.precompile(Main.scala:39)
[error] 	at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$1(Main.scala:27)
[error] 	at io.kaitai.struct.Main$.$anonfun$importAndPrecompile$1$adapted(Main.scala:24)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:251)
[error] 	at scala.util.Success.map(Try.scala:209)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:289)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[error] 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[error] 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[error] Nonzero exit code: 1
[error] (compilerJVM / Compile / run) Nonzero exit code: 1
```
</details>

**Comment by generalmimon** [comment]
Actually, that's understandable due to how `sizeof` is implemented in the current compiler. Currently, `sizeof` is designed to just yield a compile-time constant if available (an exact integer known at compile time, not involving any expressions). Read the sizeof proposal carefully (https://github.com/kaitai-io/kaitai_struct/issues/84#issue-200838598), there isn't a single mention of the possibility to generate runtime expression size calculations. I suppose that you expect this to happen at compile time:

```yaml
instances:
  sizeof_things:
    value: things.size * 1 # or num_things * 1, 1 is the number of bytes that `u1` occupies
```
 
Unfortunately, this is not how it works. That's not a integer constant that can be derived at compile-time, that's an expression. I see that it's quite stupid and agree to make it work even with sizes that have to be calculated in runtime, but I personally don't know if this design is intentional, or if this use case hadn't occurred to anyone. I hope @KOLANICH and @GreyCat could answer this.

Have you discovered this issue while solving some particular real format case or just while testing language sanity?

**Comment by dgelessus** [comment]
Ah ok, that makes sense. I thought that only the `sizeof<some_type>` variant was restricted to compile-time constant sizes, and that the `some_value._sizeof` variant was meant to also work for cases where the size is variable. Does that mean that both variants can only return compile-time constant sizes, and the only difference is that one is called on a type and the other on a value?

> Have you discovered this issue while solving some particular real format case or just while testing language sanity?

I ran into this while writing a spec for a real format. I was trying to do something similar to C's `offsetof`, i. e. I wanted to calculate the position of a field relative to the start of the struct.

I found out later from @GreyCat that in my particular case there's a better solution that doesn't require `_sizeof` (I was able to use `_io.pos` instead), but that solution only works if the stream is currently at the field for which you want to calculate the offset.

**Comment by generalmimon** [comment]
@dgelessus 
> Does that mean that both variants can only return compile-time constant sizes, and the only difference is that one is called on a type and the other on a value?

Yes, exactly.

Do you think that it would be useful to support the run-time calculated `sizeof` as well, so it would properly derive the real size even when conditionals, repetitions or type-switching are used? I'm a bit hesitating on this bit, if it really brings any value. I mean, it's probably not too simple to implement, and I don't know if it's worth the trouble.

The simplest and most reliable way working even in cases like this

```yaml
seq:
  - id: indicator
    type: u1
  - id: items
    size: 2 * (_index + 1)
    repeat: expr
    repeat-expr: 10
    if: indicator == -1
types:
  foo: {}
instances:
  bar:
    value: items._sizeof
```

... is probably to generate a method `_sizeofItems()` processing `seq` fields one after another in a similar way how it's done by the `_read()` method (maybe it should be lazy as well). In this case, it could look like this:

```java
public int _sizeofItems() {
    int size = 0;
    if (indicator == -1) {
      for (int i = 0; i < 10; i++) {
          size += 2 * (i + 1);
      }
    }
    return size;
}
```

So it can be done, but the real question is, if it would be really used, whether the implementation won't be just a waste of time. Because in most cases, it's easy to calculate the variable size with a simple expression. And if isn't, it's possible to use the trick with creating two value instances with `value: _io.pos` and invoking them just before and just after parsing the field we want to get size of:

```yaml
seq:
  - id: indicator
    type: u1
  - id: invoke_items_start
    size: 0
    if: items_start >= 0
  - id: items
    size: 2 * (_index + 1)
    repeat: expr
    repeat-expr: 10
    if: indicator == -1
  - id: invoke_items_end
    size: 0
    if: items_end >= 0
types:
  foo: {}
instances:
  items_start:
    value: _io.pos
  items_end:
    value: _io.pos
  bar:
    value: items_end - items_start # items._sizeof
```

Yeah, I agree it's a slight hack, but it works.
