### ISSUE TITLE
Extraction and parsing of rsrc in Microsoft PE files

### ISSUE THREAD

**Issue by OlivierCavadenti** [kaitai-io/kaitai_struct#816]
Hi,

I have download both Microsoft PE and Windows resource file parsers and I try to use the second to parse the rsrc section of the first.

I try this in Kotlin: 

```
    MicrosoftPe.fromFile(path)
        .pe()
        .sections()
        .forEach { section ->
            if (section.name() == ".rsrc") {
                WindowsResourceFile(ByteBufferKaitaiStream(section.body()))
                    .resources().forEach {
                        println(it.name().asString())
                    }
            }
        }
```
I have this error : 

```
Exception in thread "main" java.lang.IllegalArgumentException: Java byte arrays can be indexed only up to 31 bits, but 2147483856 size was requested
	at io.kaitai.struct.KaitaiStream.toByteArrayLength(KaitaiStream.java:294)
	at io.kaitai.struct.ByteBufferKaitaiStream.readBytes(ByteBufferKaitaiStream.java:273)
	at parsers.executable.WindowsResourceFile$Resource._read(WindowsResourceFile.java:139)
	at parsers.executable.WindowsResourceFile$Resource.<init>(WindowsResourceFile.java:126)
	at parsers.executable.WindowsResourceFile._read(WindowsResourceFile.java:63)
	at parsers.executable.WindowsResourceFile.<init>(WindowsResourceFile.java:56)
	at parsers.executable.WindowsResourceFile.<init>(WindowsResourceFile.java:45)
```

I assume that the body of the section have more complex structure that just a list of resources data but I cant find any way to successfully parse these resources with WindowsResourceFile.

Cheers

**Comment by GreyCat** [comment]
@OlivierCavadenti It looks like your `.rsc` contents fails to be parsed by WindowsResourceFile — either it's some missing feature, or the content is malformed. If you want, you can investigate this one, isolating contents of `.rsrc` into a separate file and loading it in some tooling (e.g. WebIDE or ksv) to see where the discrepancy happens, or you can attach that data here and somebody might take a look for you.
