### ISSUE TITLE
NPE if FORMATS_ERR_DIR doesn't exists or inaccessible

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#831]
The first error from https://github.com/kaitai-io/kaitai_struct_compiler/pull/219/checks?check_run_id=1437841143 is due that fact that `FORMATS_ERR_DIR` is not exists or inaccessible and [File.listFiles](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()) returns `null` in that case.
```
io.kaitai.struct.ErrorMessagesSpec *** ABORTED ***
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "$this" is null
at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:202)
at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:198)
at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:301)
at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:296)
at scala.collection.mutable.ArrayOps$ofRef.filterImpl(ArrayOps.scala:198)
at scala.collection.TraversableLike.filter(TraversableLike.scala:394)
at scala.collection.TraversableLike.filter$(TraversableLike.scala:394)
at scala.collection.mutable.ArrayOps$ofRef.filter(ArrayOps.scala:198)
at io.kaitai.struct.ErrorMessagesSpec.<init>(ErrorMessagesSpec.scala:61)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
...
```

I don't know what the right way to fix that issue. Perhaps folder should exists at this point

**Comment by generalmimon** [comment]
@Mingun `FORMATS_ERR_DIR` is this one: [**kaitai_struct_tests** / formats_err /](https://github.com/kaitai-io/kaitai_struct_tests/tree/0a5935d/formats_err)

See [**kaitai_struct_compiler** / ... / ErrorMessagesSpec.scala:17](https://github.com/kaitai-io/kaitai_struct_compiler/blob/af69228e70cfdab96eb2fc334b9b0e8aab3c52aa/jvm/src/test/scala/io/kaitai/struct/ErrorMessagesSpec.scala#L17):

```scala
  val FORMATS_ERR_DIR = "../tests/formats_err"
```

NPE is OK in this case, because it assumes the `sbt test` is run from the `compiler/` folder in the umbrella repo [**kaitai_struct**](https://github.com/kaitai-io/kaitai_struct), which also has the submodule `tests/`.
