### ISSUE TITLE
KSC 0.10-SNAPSHOT for JRE stopped displaying all error messages 

### ISSUE THREAD

**Issue by generalmimon** [kaitai-io/kaitai_struct#864]
This is obviously connected with the recent major changes regarding error reporting (https://github.com/kaitai-io/kaitai_struct_compiler/commit/2851d203be30d2e66e5d4f3b9499355c94cc415a). If you try compiling an invalid KSY which fails in the precompile phase, the compiler does not generate any files or print any error message. Take this example of a KSY that uses a `type: str` but specifies no encoding:

```ksy
meta:
  id: str_no_encoding
seq:
  - id: foo
    size: 16
    type: strz
```

```console
pp@DESKTOP-MIPASSQ MINGW64 /c/temp/kaitai_struct/tests (master)
$ kaitai-struct-compiler -- --verbose all --ksc-exceptions -t all -d compiled formats/str_no_encoding.ksy
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding="UTF-8"
home path: location = /C:/temp/kaitai_struct/compiler/jvm/target/universal/stage/lib/io.kaitai.kaitai-struct-compiler-0.10-SNAPSHOT.jar
... URL-decoded = /C:/temp/kaitai_struct/compiler/jvm/target/universal/stage/lib/io.kaitai.kaitai-struct-compiler-0.10-SNAPSHOT.jar
... home = C:\temp\kaitai_struct\compiler\jvm\target\universal\stage
... formats = C:\temp\kaitai_struct\compiler\jvm\target\universal\stage\formats
parsing formats\str_no_encoding.ksy...
reading formats\str_no_encoding.ksy...

pp@DESKTOP-MIPASSQ MINGW64 /c/temp/kaitai_struct/tests (master)
$
```

And yes, this is the full output. Only trying to generate a spec from KST for this KSY shows what's going on (but you need to create `spec/ks/str_no_encoding.kst` for it because that's how `./spec_kst_to_all` works):

```console
pp@DESKTOP-MIPASSQ MINGW64 /c/temp/kaitai_struct/tests (master)
$ ./spec_kst_to_all -t all -t go -f str_no_encoding
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding="UTF-8"
[info] welcome to sbt 1.4.3 (Oracle Corporation Java 1.8.0_271)
[info] loading project definition from C:\temp\kaitai_struct\tests\translator\project
[info] loading settings for project translator from build.sbt ...
[info] set current project to translator (in build file:/C:/temp/kaitai_struct/tests/translator/)
[warn] there's a key that's not used by any other settings/tasks:
[warn]
[warn] * translator / mainClass
[warn]   +- C:\temp\kaitai_struct\tests\translator\build.sbt:16
[warn]
[warn] note: a setting might still be used by a command; to exclude a key from this `lintUnused` check
[warn] either append it to `Global / excludeLintKeys` or call .withRank(KeyRanks.Invisible) on the key
[info] running io.kaitai.struct.testtranslator.Main -t all -t go -f str_no_encoding
Translating: str_no_encoding
../formats/str_no_encoding.ksy: /seq/0: error: string type, but no encoding found
[error] (run-main-0) java.lang.RuntimeException: Error during localFileToSpecs
[error] java.lang.RuntimeException: Error during localFileToSpecs
[error]         at io.kaitai.struct.testtranslator.TestTranslator.loadClassSpecs(TestTranslator.scala:64)
[error]         at io.kaitai.struct.testtranslator.TestTranslator.doTestSpec(TestTranslator.scala:26)
[error]         at io.kaitai.struct.testtranslator.TestTranslator.$anonfun$run$1(TestTranslator.scala:18)
[error]         at io.kaitai.struct.testtranslator.TestTranslator.$anonfun$run$1$adapted(TestTranslator.scala:17)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at io.kaitai.struct.testtranslator.TestTranslator.run(TestTranslator.scala:17)
[error]         at io.kaitai.struct.testtranslator.Main$.delayedEndpoint$io$kaitai$struct$testtranslator$Main$1(Main.scala:99)
[error]         at io.kaitai.struct.testtranslator.Main$delayedInit$body.apply(Main.scala:8)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:80)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at scala.App.main(App.scala:80)
[error]         at scala.App.main$(App.scala:78)
[error]         at io.kaitai.struct.testtranslator.Main$.main(Main.scala:8)
[error]         at io.kaitai.struct.testtranslator.Main.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 3 s, completed 21.3.2021 22:57:48

pp@DESKTOP-MIPASSQ MINGW64 /c/temp/kaitai_struct/tests (master)
$
```

**Comment by KOLANICH** [comment]
I confirm that the issue exists.
