### ISSUE TITLE
[compilerJVM/universal] UnsupportedOperationException: The Security Manager is deprecated

### ISSUE THREAD

**Issue by cso-idn-player** [kaitai-io/kaitai_struct#974]
Tried to build universal java zip by following this guide,
http://doc.kaitai.io/developers.html#_building_for_jvm
but got an exception.

```
D:\Git\kaitai_struct\compiler>sbt compilerJVM/universal:packageBin
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at sbt.TrapExit$.installManager(TrapExit.scala:54)
        at sbt.StandardMain$.runManaged(Main.scala:184)
        at sbt.xMain$.$anonfun$run$6(Main.scala:100)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:553)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:343)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:543)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:543)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:343)
        at sbt.xMain$.run(Main.scala:83)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:83)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
[error] [launcher] error during sbt launcher: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
```

My environments:
```
D:\Git\kaitai_struct\compiler>git status
HEAD detached at 0a3dcbfb
nothing to commit, working tree clean

D:\Git\kaitai_struct\compiler>java --version
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)

D:\Git\kaitai_struct\compiler>scala --version
Scala code runner version 2.13.8 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.

D:\Git\kaitai_struct\compiler>sbt --version
sbt version in this project: [launcher]
sbt script version: 1.6.2
```

Current workaround is by using [development version of Kaitai Web IDE](https://ide.kaitai.io/devel/).

**Comment by cso-idn-player** [comment]
Downgraded to temurin16-jdk and seems able to compile it with 58 warnings.
```
openjdk 16.0.2 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
```

Console log:
https://pastebin.com/5Qb05pS1

**Comment by generalmimon** [comment]
Yeah, I'm afraid you unfortunately can't use Java 18 yet (until we update the Scala version, sbt version and dependencies of the KS compiler, but that can't be done lightly because we have to check many things that can go wrong):

```console
D:\Git\kaitai_struct\compiler>java --version
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Temurin-18.0.1+10 (build 18.0.1+10)
OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (build 18.0.1+10, mixed mode, sharing)
```

BTW, the versions you print like this mean nothing:

```console
D:\Git\kaitai_struct\compiler>scala --version
Scala code runner version 2.13.8 -- Copyright 2002-2021, LAMP/EPFL and Lightbend, Inc.

D:\Git\kaitai_struct\compiler>sbt --version
sbt version in this project: [launcher]
sbt script version: 1.6.2
```

This is because AFAIK `sbt` that you installed will only be used as a downloader for the versions according to `build.sbt` and `project/build.properties` in the KSC project repo:

[`build.sbt:28`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/54691da3f80162b0b1f7cdc120fbbf244daf288b/build.sbt#L28)

```sbt
    scalaVersion := "2.12.12",
```

[`project/build.properties:1`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/54691da3f80162b0b1f7cdc120fbbf244daf288b/project/build.properties#L1)

```properties
sbt.version = 1.4.3
```

See https://github.com/sbt/sbt/issues/6558.

**Comment by cso-idn-player** [comment]
```
BTW, the versions you print like this mean nothing:

This is because AFAIK sbt that you installed will only be used as a downloader for the versions according to build.sbt and project/build.properties in the KSC project repo:
```
Ah, sorry. i don't aware of it since this is my first time to use it.

**Comment by generalmimon** [comment]
@cso-idn-player:
> Downgraded to temurin16-jdk and seems able to compile it

Great!

> with 58 warnings.

Warnings are normal. Frankly, we only have so much time and there are plenty of higher priority and more serious issues, rather than making `sbt` happy.

It's true that we could raise the `logLevel` to `Level.Error` (https://stackoverflow.com/a/31936797). That should silence the warnings.

**Comment by cso-idn-player** [comment]
No problem. Thankfully, i'm able to build it now.
But, unfortunately, my ksy script issue still persist, but that one may need a separate git issue thread.
May close this issue.
