### ISSUE TITLE
Import issue with KSV 

### ISSUE THREAD

**Issue by nosajthenitram** [kaitai-io/kaitai_struct#985]
I'm attempting to import my 6th ksy file into my main ksy, but when I run ksv, the interface hangs. When I interrupt it with ctrl-c, it shows the following stack: 

`^CTraceback (most recent call last):
        11: from /usr/local/bin/ksv:23:in `<main>'
        10: from /usr/local/bin/ksv:23:in `load'
         9: from /var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/bin/ksv:53:in `<top (required)>'
         8: from /var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/visualizer.rb:13:in `run'
         7: from /var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/parser.rb:25:in `load'
         6: from /var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/ksy_compiler.rb:19:in `compile_formats'
         5: from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
         4: from /var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/ksy_compiler.rb:39:in `block in compile_formats'
         3: from /usr/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         2: from /usr/lib/ruby/2.7.0/open3.rb:219:in `popen_run'
         1: from /var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/ksy_compiler.rb:40:in `block (2 levels) in compile_formats'
/var/lib/gems/2.7.0/gems/kaitai-struct-visualizer-0.7/lib/kaitai/struct/visualizer/ksy_compiler.rb:40:in `value': Interrupt`

Is there a limit to the number of imports supported?

**Comment by generalmimon** [comment]
@nosajthenitram Can you please try compiling your .ksy file directly with `kaitai-struct-compiler`? Something like:

```
kaitai-struct-compiler --debug -t ruby --outdir outdir/ root.ksy
```

**Comment by nosajthenitram** [comment]
@generalmimon compiled does not hang, just KSV. Separate repo and issue to be created?

**Comment by generalmimon** [comment]
> Separate repo and issue to be created?

I can just transfer this one to https://github.com/kaitai-io/kaitai_struct_visualizer, hang on a second...
